"""Data literals and pure helpers used by main.py (Layer 1 extraction)."""

import base64
from pathlib import Path

import streamlit as st


@st.cache_data
def load_favicon_b64() -> str:
    """Reads the local favicon PNG and returns its base64-encoded string."""
    favicon_bytes = (Path(__file__).resolve().parent / "assets" / "favicon.png").read_bytes()
    return base64.b64encode(favicon_bytes).decode()


# Teal, single-color (feather-style) icon set - replaces emoji so nav-card icons
# match the canonical teal accent instead of the OS's full-color emoji glyphs.
NAV_ICONS: dict[str, str] = {
    "layers": '<polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline>',
    "refresh-cw": '<polyline points="23 4 23 10 17 10"></polyline><polyline points="1 20 1 14 7 14"></polyline><path d="M3.51 9a9 9 0 0114.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0020.49 15"></path>',
    "database": '<ellipse cx="12" cy="5" rx="9" ry="3"></ellipse><path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3"></path><path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"></path>',
    "search": '<circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line>',
    "alert-octagon": '<polygon points="7.86 2 16.14 2 22 7.86 22 16.14 16.14 22 7.86 22 2 16.14 2 7.86 7.86 2"></polygon><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line>',
    "git-branch": '<line x1="6" y1="3" x2="6" y2="15"></line><circle cx="18" cy="6" r="3"></circle><circle cx="6" cy="18" r="3"></circle><path d="M18 9a9 9 0 01-9 9"></path>',
    "shield": '<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path>',
    "zap": '<polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"></polygon>',
    "send": '<line x1="22" y1="2" x2="11" y2="13"></line><polygon points="22 2 15 22 11 13 2 9 22 2"></polygon>',
}


def nav_icon(name: str, size: int = 20) -> str:
    """Builds an inline teal SVG icon for a nav-card, keyed by name in NAV_ICONS."""
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}" viewBox="0 0 24 24" '
            f'fill="none" stroke="#21918c" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" '
            f'style="vertical-align:-4px;margin-right:8px;">{NAV_ICONS[name]}</svg>')


# 9-Module List for the 3x3 Grid: (page path, icon name, title, description)
NAV_MODULES: list[tuple[str, str, str, str]] = [
    ("pages/0001_Foundations.py", "layers", "Foundations",
     "Project Timeline, bottom-up strategy, pivot to classification, and the target variable definition."),
    ("pages/0002_Acquisition_Pipelines.py", "refresh-cw", "Acquisition Pipelines",
     "Dual-engine data collection: GTS Telemetry Emulator and Gemini OCR Pipeline."),

    ("pages/0003_Feature_Store.py", "database", "Feature Store",
     "Documents the Bronze/Silver/Gold medallion pipeline that enriches raw OCR output into the model's feature vector."),

    ("pages/0004_Data_Census_(The_Basics).py", "search", "Data Census",
     "Establishes the relational schema and surfaces the baseline census across product mix, incentives, traffic, and profitability."),

    ("pages/0005_The_Cost_of_Patience.py", "alert-octagon", "The Cost of Patience",
     "Analyzes market volatility, opportunity flow, and derives rational search time boundaries via Continuation Value."),

    ("pages/0006_Payout_Physics_Causal_Inference.py", "git-branch", "Payout Physics",
     "Audits payout stability and formalizes the platform's price-integrity mechanisms via heteroscedasticity and non-linear modeling."),

    ("pages/0007_Human_vs_AI_Behavioral_Cloning.py", "shield", "Human vs AI",
     "A hierarchical multiclass architecture that clones the agent's decision policy, diagnosing why flat models fail on nuanced, minority-class decisions."),

    ("pages/0008_The_Quest_to_O1_NLP.py", "zap", "The Quest to (O)1",
     "A custom NLP Transformer that replaces Cloud geocoding — 78x faster, sub-10ms local inference."),

    ("pages/0009_Generative_Moonshots:_pienza_big.py", "send", "Generative Moonshots",
     "A synthetic manifold generated by cGANs, powering a Markov scaffolding for Reinforcement Learning."),
]
