import streamlit as st
import streamlit.components.v1 as components
from components.sidebar import build_sidebar
from components.styles import GLOBAL_CSS
from config import FAVICON, build_page_title
from pathlib import Path
from _main_data import NAV_MODULES, nav_icon
from utils.mem_debug import log_mem

log_mem("main.py top")

st.set_page_config(layout="wide", page_title=build_page_title("Home"), page_icon=FAVICON)

# --- 0. SIDEBAR INTEGRADA ---
build_sidebar()


st.markdown(GLOBAL_CSS, unsafe_allow_html=True)

# Page-specific overrides (kept empty on purpose — matches the vertical
# rhythm of 0001/0002's own style block so the title sits at the same
# height across pages; this extra st.markdown() call is what supplies
# Streamlit's default inter-widget gap before the H1)
st.markdown("<style></style>", unsafe_allow_html=True)

# --- 3. HERO HEADER ---
st.markdown("# Project Pienza")

st.write("") # Spacer

# --- 4. THE KILLER NARRATIVE & ACHIEVEMENTS ---
st.markdown("""
<div style="font-family:'Inter',sans-serif;font-size:14px;font-weight:400;color:#475569;line-height:1.7;margin-bottom:24px;">
<b>Pienza</b> is an independent, end-to-end Data Science research initiative that captures the proven—yet tacit—heuristics of street-level ride-hailing in Mexico City.
<br><br>
Engineered to overcome survivorship bias by digitizing the agent's full decision boundaries over a 6-week field acquisition window, Pienza executes the entire data lifecycle: from raw extraction and feature engineering, through schema reconciliation (<code style="color:#158237;font-family:'Source Code Pro',monospace;font-size:0.75rem;background:transparent;">pienza.db</code>), to causal audits, supervised learning, and an NLP Transformer.
<br><br>
Ultimately, with a 1M-row synthetic manifold generated by cGANs, Pienza bridges the gap between behavioral cloning and sequential decision science via a graph-based Markov sandbox for autonomous execution.
</div>
""", unsafe_allow_html=True)

st.write("") # Spacer

st.markdown("""

<div class="bento-grid">
    <div class="bento-card">
        <div class="bento-title">Telemetry Ledger</div>
        <div class="bento-value">4,700+</div>
        <div class="bento-desc">Ride offers and market interactions captured via a dual-engine OCR system.</div>
    </div>
    <div class="bento-card">
        <div class="bento-title">Generative Scale</div>
        <div class="bento-value">1M Rows</div>
        <div class="bento-desc">Operational manifold synthesized using cGANs.</div>
    </div>
    <div class="bento-card">
        <div class="bento-title">Spatial Latency</div>
        <div class="bento-value">< 10ms</div>
        <div class="bento-desc">Real-time inference via the miniBabel NLP Transformer.</div>
    </div>
    <div class="bento-card">
        <div class="bento-title">Markov Decision Process</div>
        <div class="bento-value">5-Jump</div>
        <div class="bento-desc">Optimized mission sequences derived via a prescriptive Q-Matrix policy.</div>
    </div>
</div>
""", unsafe_allow_html=True)

st.markdown("""
<div style="height: 50px;"></div>
""", unsafe_allow_html=True)

# --- 5. THE HERO VISUAL (3D MANIFOLD) ---
st.markdown("### The Playground: Machine Discovered Hubs")

# @st.fragment isolates this iframe from full-page reruns (e.g. clicking
# Flush Cache or the PDF button elsewhere on the page) — without it,
# components.html() re-injects the whole Kepler.gl HTML on every rerun,
# forcing the browser to reinitialize WebGL/deck.gl from scratch even
# though the map itself never changes.
@st.fragment
def _render_kepler_hero():
    try:
        html_data = (Path(__file__).resolve().parent / "assets" / "kepler_3D.html").read_text(encoding="utf-8")

        # Kepler.gl's exported HTML briefly renders its own factory-default
        # viewport (San Francisco) before its JS bundle finishes parsing and
        # dispatching the saved CDMX mapState — a Kepler boot-sequence quirk,
        # not a bug in the exported data (confirmed 2026-07-09, see
        # project_tech_debt memory). A fixed setTimeout was tried here before
        # and caused a worse regression on Streamlit Cloud (permanently blank
        # map, only fixed by a manual reload) — Cloud's cold-start load time
        # is unpredictable, so a fixed delay can fire either too early (flash
        # still visible) or, if something else delays rendering, the hidden
        # state can get stuck with no way to recover.
        # Fix: reveal as soon as the WebGL canvas Kepler/Mapbox creates
        # actually appears in the DOM (a real signal the map has painted,
        # not a guess), polled every 100ms. A hard 4s safety timeout always
        # forces the reveal regardless, so the map can never stay invisible
        # forever even if the canvas selector ever stops matching (e.g. a
        # future Kepler/Mapbox version renaming its canvas class).
        force_white_css = """
<style>
body { background-color: white !important; opacity: 0; transition: opacity 0.3s ease; }
</style>
<script>
(function () {
  var revealed = false;
  function reveal() {
    if (revealed) return;
    revealed = true;
    document.body.style.opacity = 1;
  }
  var checkInterval = setInterval(function () {
    if (document.querySelector('canvas')) {
      clearInterval(checkInterval);
      reveal();
    }
  }, 100);
  setTimeout(function () {
    clearInterval(checkInterval);
    reveal();
  }, 4000);
})();
</script>
"""
        components.html(force_white_css + html_data, height=600)

    except Exception as e:
        st.error(f"Failed to load Kepler map: {e}")

_render_kepler_hero()

st.markdown(
    "<div style='margin-top:-15px;margin-bottom:32px;font-size:0.65rem;color:#64748b;font-style:italic;'>"
    "Manifold Visualization: 44 HDBSCAN clusters defining the primary decision playground. "
    "Height represents offer density; color encodes topological gravity wells. Clusters are "
    "highlighted against the Agent's hand-crafted polygons representing the operational zone theatre."
    "</div>",
    unsafe_allow_html=True,
)

# --- 6. NAVIGATE THE OBSERVATORY ---
st.markdown("### The Observatory Architecture")
st.markdown(
    "<div style=\"font-family:'Inter',sans-serif;font-size:13px;font-weight:400;color:#475569;line-height:1.7;margin-bottom:4px;\">"
    "Navigate through the core modules of the Pienza digital twin.</div>",
    unsafe_allow_html=True,
)

# Inject the Bento Aesthetic CSS targeting our specific containers with high specificity
st.markdown("""
<style>
/* All nav-card rules target [class*="st-key-nav-card-"] - the stable class Streamlit
   attaches to a container via st.container(key=...). Deliberately NOT using :has() -
   div[data-testid="stVerticalBlockBorderWrapper"]:has(.nav-card) was confirmed unreliable
   in this Streamlit version (height/background/hover rules silently didn't apply; see
   project_tech_debt.md). Plain descendant selectors (no :has) worked fine throughout,
   so this keyed-class approach avoids the broken mechanism entirely. */

/* 1. Base card style (mimics ingestion-panel) */
div[class*="st-key-nav-card-"] {
    background-color: #ffffff !important;
    border: 1px solid #eaeaea !important;
    border-radius: 16px !important;
    padding: 20px !important;
    transition: transform 0.25s ease-out, box-shadow 0.25s ease-out, border-color 0.25s ease-out !important;
    box-shadow: 0 4px 6px rgba(0,0,0,0.02) !important;
    height: 300px !important;
    overflow: hidden !important;
}

/* 1b. Stack card contents vertically and pin the button to the bottom */
div[class*="st-key-nav-card-"] > div[data-testid="stVerticalBlock"] {
    height: 100% !important;
    display: flex !important;
    flex-direction: column !important;
    justify-content: space-between !important;
}

/* 2. Card hover effect (lift + scale + teal outline) */
div[class*="st-key-nav-card-"]:hover {
    transform: translateY(-6px) scale(1.015) !important;
    box-shadow: 0 12px 24px rgba(0,0,0,0.08) !important;
    border-color: #21918c !important; /* Teal outline */
}

/* 3. Navigation button style (st.page_link) - target both the legacy class
   and the data-testid, since Streamlit versions differ in which one is present */
div[class*="st-key-nav-card-"] .stPageLink a,
div[class*="st-key-nav-card-"] [data-testid="stPageLink"] a {
    display: flex !important;
    align-items: center !important;
    justify-content: center !important;
    text-align: center !important;
    background-color: #f0f2f5 !important;
    color: #64748b !important;
    padding: 6px 10px !important;
    border-radius: 8px !important;
    text-decoration: none !important;
    transition: background-color 0.2s ease-in-out, color 0.2s ease-in-out !important;
    width: 100% !important;
    border: none !important;
}

/* 4. Button hover (faint teal, slightly darker than the fixed grey) */
div[class*="st-key-nav-card-"] .stPageLink a:hover,
div[class*="st-key-nav-card-"] [data-testid="stPageLink"] a:hover {
    background-color: rgba(33,145,140,0.14) !important;
    color: #21918c !important;
}

/* 5. Centered button text */
div[class*="st-key-nav-card-"] .stPageLink a p,
div[class*="st-key-nav-card-"] [data-testid="stPageLink"] a p {
    color: inherit !important;
    margin: 0 !important;
    font-weight: 500 !important;
    font-size: 0.8rem !important;
    text-align: center !important;
    width: 100% !important;
}
</style>
""", unsafe_allow_html=True)

# Create a 3-column grid layout for visually stunning, concise cards
cols = st.columns(3)

for i, (path, icon, title, desc) in enumerate(NAV_MODULES):
    with cols[i % 3]:
        with st.container(border=True, key=f"nav-card-{i}"):
            # Fixed-height content block (icon+title+desc) we fully control, so total
            # card height stays constant regardless of description length.
            st.markdown(
                f"<div style='height:135px;display:flex;flex-direction:column;overflow:hidden;'>"
                f"<div style='font-size:1.05rem;font-weight:700;line-height:1.3;margin-bottom:8px;'>{nav_icon(icon)}{title}</div>"
                f"<p style='font-size:13px;font-weight:400;color:#475569;line-height:1.7;flex:1;overflow:hidden;"
                f"display:-webkit-box;-webkit-line-clamp:4;-webkit-box-orient:vertical;margin:0;'>{desc}</p>"
                f"</div>",
                unsafe_allow_html=True,
            )
            st.page_link(path, label="Explore Module", use_container_width=True)

st.markdown("---")

# --- 7. PROJECT DISCLAIMER ---
st.markdown(
    "<div style='text-align:center;color:#94a3b8;font-size:0.75rem;font-style:italic;"
    "line-height:1.6;max-width:900px;margin:0 auto;'>"
    "Project Pienza and all associated materials are the product of an independent research "
    "initiative, aimed at formalizing sequential decision boundaries in stochastic environments. "
    "The dataset and presented architecture are fully operational and derived from authentic, "
    "high-fidelity field telemetry captured via AI-assisted optical extraction pipelines during a "
    "controlled longitudinal observation window. All models reflect real empirical execution. To "
    "ensure strict compliance with applicable personal data protection regulations, third-party "
    "terms of service, and the privacy of proprietary information, all source assets were subjected "
    "to a multi-layered, non-destructive anonymization protocol, obfuscating the platform's "
    "proprietary metrics while fully preserving the mathematical properties, probability "
    "distributions, and behavioral physics of the underlying market. The content is not intended "
    "for, and should not be used for, any commercial, financial, or business operations."
    "</div>",
    unsafe_allow_html=True,
)

# --- 7. FOOTER ---
st.markdown("---")
st.markdown(
    "<div style='text-align: center; color: gray; font-size: 0.8rem;'>"
    "Lozano Wise, B. (2026). Project Pienza. Independent Research Initiative."
    "</div>", 
    unsafe_allow_html=True
)