[theme]
primaryColor = "#21918c" # Your Opus Teal
backgroundColor = "#F5F6F7"
secondaryBackgroundColor = "#E8E8E8"
textColor = "#121212"
font = "sans serif"
base = "light"

[client]
showSidebarNavigation = false

[server]
runOnSave = true