import time

import numpy as np
import requests
import streamlit as st

from components.sidebar import build_sidebar
from components.styles import GLOBAL_CSS
from config import FAVICON, build_page_title
from utils.gcp_client import fetch_parquet_from_gcp
from utils.gcp_auth import get_gcp_credentials
from utils.vertex_embed import embed_text

# ==========================================
# PAGE CONFIGURATION
# ==========================================
st.set_page_config(page_title=build_page_title("RAG Assistant"), page_icon=FAVICON, layout="wide")

build_sidebar()
st.markdown(GLOBAL_CSS, unsafe_allow_html=True)
st.markdown("<style></style>", unsafe_allow_html=True)

st.markdown("# RAG Assistant")
st.markdown(
    "<h4 style='font-weight:300; color:#21918c; font-size:19px; margin:-10px 0 20px;'>"
    "Retrieval-Augmented Generation over Pienza's own project documentation</h4>",
    unsafe_allow_html=True,
)
st.markdown(
    """
    <p style='font-size:14px;font-weight:400;color:#475569;line-height:1.7;margin-bottom:16px;'>
    Ask a question about how this project works. The answer is generated by Claude, grounded
    only in the retrieved passages shown below each response — not from the model's general
    knowledge. Embeddings come from Vertex AI (<code>text-embedding-004</code>); retrieval is a
    plain cosine-similarity search over a small, precomputed corpus — no vector database needed
    at this scale.
    </p>
    """,
    unsafe_allow_html=True,
)

PROJECT_ID = "drivers-dilemma"
CORPUS_BUCKET = "pienza-streamlit"
CORPUS_FILE = "rag_corpus_claude_docs.parquet"
TOP_K = 4
CLAUDE_MODEL = "claude-haiku-4-5-20251001"


@st.cache_data(show_spinner="Loading RAG corpus...")
def load_corpus():
    df = fetch_parquet_from_gcp(CORPUS_BUCKET, CORPUS_FILE)
    if df.empty:
        return df, None
    matrix = np.stack(df["embedding"].to_numpy())
    return df, matrix


def retrieve(question: str, df, matrix, k: int = TOP_K):
    credentials = get_gcp_credentials()
    query_vec = np.array(embed_text(question, PROJECT_ID, credentials))
    sims = matrix @ query_vec / (np.linalg.norm(matrix, axis=1) * np.linalg.norm(query_vec) + 1e-10)
    top_idx = np.argsort(-sims)[:k]
    return df.iloc[top_idx].assign(similarity=sims[top_idx])


def ask_claude(question: str, chunks) -> str:
    api_key = st.secrets.get("ANTHROPIC_API_KEY", "")
    if not api_key:
        return "ANTHROPIC_API_KEY missing from secrets — cannot generate an answer."

    context = "\n\n".join(
        f"[Source: {row.source_file} — {row.heading}]\n{row.text}" for row in chunks.itertuples()
    )
    system_prompt = (
        "You are a documentation assistant for Project Pienza, a Streamlit Observatory. "
        "Answer the user's question using ONLY the provided context passages. "
        "If the context doesn't contain the answer, say so plainly instead of guessing. "
        "Cite the source_file of the passage(s) you used in your answer."
    )
    resp = requests.post(
        "https://api.anthropic.com/v1/messages",
        headers={
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        },
        json={
            "model": CLAUDE_MODEL,
            "max_tokens": 1024,
            "system": system_prompt,
            "messages": [
                {"role": "user", "content": f"Context:\n\n{context}\n\nQuestion: {question}"}
            ],
        },
        timeout=30,
    )
    if resp.status_code != 200:
        return f"Claude API error ({resp.status_code}): {resp.text[:300]}"
    data = resp.json()
    return "".join(b.get("text", "") for b in data.get("content", []) if b.get("type") == "text")


corpus_df, corpus_matrix = load_corpus()

if corpus_df is None or corpus_df.empty:
    st.markdown(
        """
        <div style='border-left:6px solid #ffe600;background:#ffff00;border-radius:0 8px 8px 0;
             padding:12px 16px;margin-top:10px;font-size:0.80rem;color:#1a1a1a;line-height:1.65;'>
          <span style='font-size:0.7rem;font-weight:900;text-transform:uppercase;letter-spacing:0.8px;
                color:#cc6600;'>⚠ PENDING FIX — Corpus not found</span><br><br>
          Could not load <code>rag_corpus_claude_docs.parquet</code> from GCS. Confirm the file was
          uploaded to bucket <code>pienza-streamlit</code>.
        </div>
        """,
        unsafe_allow_html=True,
    )
    st.stop()

question = st.text_input("Ask a question about Project Pienza", placeholder="e.g. what's the anonymization rule for addresses?")

if question:
    with st.spinner("Retrieving relevant passages..."):
        t0 = time.perf_counter()
        top_chunks = retrieve(question, corpus_df, corpus_matrix)
        retrieval_ms = (time.perf_counter() - t0) * 1000

    with st.spinner("Generating answer..."):
        t0 = time.perf_counter()
        answer = ask_claude(question, top_chunks)
        generation_ms = (time.perf_counter() - t0) * 1000

    st.markdown(
        f"""
        <div class="bento-card" style="margin-top:12px;">
          <div class="bento-desc" style="font-size:0.95rem;color:#1a1a1a;line-height:1.7;">{answer}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.caption(f"Retrieval: {retrieval_ms:.0f} ms · Generation: {generation_ms:.0f} ms · Model: {CLAUDE_MODEL}")

    st.markdown("#### Retrieved sources")
    for row in top_chunks.itertuples():
        st.markdown(
            f"""
            <div class="bento-card" style="margin-bottom:8px;">
              <span class="story-pill">{row.source_file}</span>
              <span style="font-size:0.75rem;color:#94a3b8;margin-left:8px;">similarity {row.similarity:.2f}</span>
              <div style="font-size:0.8rem;color:#475569;margin-top:8px;line-height:1.6;">{row.text[:400]}{"..." if len(row.text) > 400 else ""}</div>
            </div>
            """,
            unsafe_allow_html=True,
        )
