import time

import pandas as pd
import streamlit as st

from components.sidebar import build_sidebar
from components.styles import GLOBAL_CSS
from config import FAVICON, build_page_title
from _main_data import svg_data_uri
from pages._0010_data import (
    CORPORA, CLAUDE_MODEL, MAX_HISTORY_TURNS, load_corpus, retrieve,
    load_trip_collection, retrieve_trips, ask_claude, ask_claude_agentic,
    format_token_count, SYSTEM_PROMPT, REASONING_SYSTEM_PROMPT, SAMPLE_QUESTIONS,
    load_eval_comparison,
)

# ==========================================
# PAGE CONFIGURATION
# ==========================================
st.set_page_config(page_title=build_page_title("RAG Assistant"), page_icon=FAVICON, layout="wide")

build_sidebar()
st.markdown(GLOBAL_CSS, unsafe_allow_html=True)
st.markdown("<style></style>", unsafe_allow_html=True)

st.markdown("# RAG Assistant")
st.markdown(
    "<h4 style='font-weight:300; color:#21918c; font-size:19px; margin:-10px 0 20px;'>"
    "Retrieval-Augmented Generation over Pienza's own project documentation</h4>",
    unsafe_allow_html=True,
)
st.markdown(
    """
    <p style='font-size:14px;font-weight:400;color:#475569;line-height:1.7;margin-bottom:16px;'>
    Ask a question about how this project works. Answers are generated by Claude, grounded only
    in passages retrieved via Vertex AI (<code>text-embedding-004</code>) embeddings. Pick the
    corpus yourself under <b>Manual Retrieval</b>, or let Claude pick it via tool-use routing
    under <b>Agentic RAG</b>.
    </p>
    """,
    unsafe_allow_html=True,
)

st.markdown(
    """
    <style>
    [data-testid="stChatMessageAvatarUser"],
    [data-testid="stChatMessageAvatarAssistant"] {
        background-color: rgba(33,145,140,0.10);
    }
    </style>
    """,
    unsafe_allow_html=True,
)

def _render_stepper():
    """Corpus selector — horizontal stepper (same visual pattern as 0008's
    ci-stepper), driving hidden st.tabs. Only relevant to Manual Retrieval —
    Agentic RAG has no stepper, the model picks the corpus itself. More
    corpora append to CORPORA in _0010_data.py, not to this markup."""
    st.markdown(
        """
<style>
.corpus-stepper { display:flex; align-items:flex-start; gap:0; margin:18px 0 6px 0; }
.corpus-step {
  display:flex; flex-direction:column; align-items:center; flex:1;
  position:relative; cursor:pointer;
}
.corpus-step:not(:last-child)::after {
  content:''; position:absolute; top:14px; left:calc(50% + 14px);
  width:calc(100% - 28px); height:2px; background:rgba(33,145,140,0.2); z-index:0;
}
.corpus-dot {
  width:28px; height:28px; border-radius:50%;
  background:rgba(33,145,140,0.12); border:1.5px solid rgba(33,145,140,0.4);
  display:flex; align-items:center; justify-content:center;
  font-size:0.60rem; font-weight:700; color:#21918c;
  z-index:1; position:relative; flex-shrink:0;
  transition: background 0.15s, border-color 0.15s;
}
.corpus-step:hover .corpus-dot { background:rgba(33,145,140,0.22); border-color:#21918c; }
.corpus-step-label {
  font-size:0.68rem; font-weight:600; color:#334155;
  text-align:center; margin-top:6px; line-height:1.3;
}
.corpus-step-sub {
  font-size:0.60rem; color:#64748b;
  text-align:center; margin-top:2px; line-height:1.3;
}
.corpus-step-tokens {
  font-size:0.58rem; color:#94a3b8;
  text-align:center; margin-top:1px; line-height:1.3;
}
.corpus-step:hover .corpus-step-label { color:#21918c; }
.corpus-step.corpus-active .corpus-dot {
  background:#21918c !important; border-color:#21918c !important; color:#fff !important;
}
.corpus-step.corpus-active .corpus-step-label { color:#21918c !important; font-weight:700; }
</style>
""" + "<div class=\"corpus-stepper\">" + "".join(
    f'<div class="corpus-step{" corpus-active" if i == 0 else ""}">'
    f'<div class="corpus-dot">C{i+1}</div>'
    f'<div class="corpus-step-label">{c["label"]}</div>'
    f'<div class="corpus-step-sub">{c["sub"]}</div>'
    f'<div class="corpus-step-tokens">{format_token_count(c["tokens"])}</div>'
    f'</div>'
    for i, c in enumerate(CORPORA)
) + "</div>", unsafe_allow_html=True)

    st.markdown(
        """
<style>
[data-baseweb="tab-panel"] [data-baseweb="tab-list"] { display:none !important; }
[data-baseweb="tab-panel"] [data-baseweb="tab-border"] { display:none !important; }
</style>
""",
        unsafe_allow_html=True,
    )

    st.components.v1.html(
        """
<script>
setTimeout(function() {
  var stepperDiv = window.parent.document.querySelector('.corpus-stepper');
  var scope = (stepperDiv && stepperDiv.closest('[data-baseweb="tab-panel"]')) || window.parent.document;
  var steps = scope.querySelectorAll('.corpus-step');
  var allTabs = scope.querySelectorAll('[data-baseweb="tab"]');

  function setActive(idx) {
    steps.forEach(function(s) { s.classList.remove('corpus-active'); });
    if (steps[idx]) steps[idx].classList.add('corpus-active');
  }

  var initIdx = 0;
  for (var j = 0; j < allTabs.length; j++) {
    if (allTabs[j].getAttribute('aria-selected') === 'true') { initIdx = j; break; }
  }
  setActive(initIdx);

  steps.forEach(function(step, i) {
    step.addEventListener('click', function() {
      var target = allTabs[i];
      if (target) {
        var sy = window.parent.scrollY;
        target.click();
        setActive(i);
        setTimeout(function() { window.parent.scrollTo(0, sy); }, 50);
        setTimeout(function() { window.parent.scrollTo(0, sy); }, 300);
      }
    });
  });
}, 300);
</script>
""",
        height=0,
    )


CORPUS_REFRESH_NOTE: dict[str, str] = {
    "claude_docs": (
        "<b>C1: Project Docs</b> (<code>.claude/claude_docs/</code>) refreshes "
        "automatically — a nightly GitHub Action re-embeds and re-uploads it to stay "
        "in sync with the repo."
    ),
    "paper": (
        "<b>C2: The Pienza Papers</b> is sourced from the <code>paper-dev</code> "
        "branch's <code>.tex</code> chapters (fetched via <code>git show</code>, no "
        "checkout) — rebuilt manually, not on an automated schedule."
    ),
    "trips": (
        "<b>C3: Trip Records</b> is sourced from BigQuery's "
        "<code>v_ML_Supervised</code> view, serialized row-to-text and stored in "
        "ChromaDB — rebuilt manually, not on an automated schedule. "
        "<span class=\"fn-wrap\"><span class=\"fn-mark\">RAG Limitation</span>"
        "<span class=\"fn-tooltip\">Top-k retrieval can't answer aggregations "
        "(ranges, counts, averages) — that needs a full table scan, which is a "
        "Text-to-SQL problem, not RAG.</span></span>"
    ),
    "codebase": (
        "<b>C4: Codebase</b> is sourced from <code>observatory/</code>'s own Python "
        "files, AST-chunked per function/class — rebuilt manually, not on an "
        "automated schedule."
    ),
}


def _render_corpus_tab(corpus: dict):
    is_chromadb = corpus.get("kind") == "chromadb"

    if is_chromadb:
        collection = load_trip_collection()
        corpus_empty = collection.count() == 0
        missing_hint = "the ChromaDB store under gcs://pienza-streamlit/chroma_trips/"
    else:
        corpus_df, corpus_matrix = load_corpus(corpus["file"])
        corpus_empty = corpus_df is None or corpus_df.empty
        missing_hint = f"<code>{corpus['file']}</code>"

    if corpus_empty:
        st.markdown(
            f"""
            <div style='border-left:6px solid #ffe600;background:#ffff00;border-radius:0 8px 8px 0;
                 padding:12px 16px;margin-top:10px;font-size:0.80rem;color:#1a1a1a;line-height:1.65;'>
              <span style='font-size:0.7rem;font-weight:900;text-transform:uppercase;letter-spacing:0.8px;
                    color:#cc6600;'>⚠ PENDING FIX — Corpus not found</span><br><br>
              Could not load {missing_hint} from GCS. Confirm the file was
              uploaded to bucket <code>pienza-streamlit</code>.
            </div>
            """,
            unsafe_allow_html=True,
        )
        return

    st.markdown(
        f"""
        <p style='font-size:14px;font-weight:400;color:#475569;line-height:1.7;margin-bottom:8px;'>
        {CORPUS_REFRESH_NOTE.get(corpus["key"], "")}
        </p>
        """,
        unsafe_allow_html=True,
    )

    history_key = f"history_{corpus['key']}"
    summary_key = f"summary_{corpus['key']}"
    mode_key = f"mode_{corpus['key']}"
    if history_key not in st.session_state:
        st.session_state[history_key] = []
    if summary_key not in st.session_state:
        st.session_state[summary_key] = ""
    if mode_key not in st.session_state:
        st.session_state[mode_key] = "strict"

    st.markdown(
        """
        <p style='font-size:14px;font-weight:400;color:#475569;line-height:1.7;margin-bottom:8px;'>
        Toggle between two system prompts: <b>Strict Grounding</b> only answers from
        retrieved context; <b>Reasoning Mode</b> may extrapolate but must disclose it.
        Expand below to see the exact system prompt for each mode.
        </p>
        """,
        unsafe_allow_html=True,
    )

    mode_col1, mode_col2 = st.columns([1, 3])
    with mode_col1:
        reasoning_on = st.toggle(
            "Reasoning Mode",
            value=(st.session_state[mode_key] == "reasoning"),
            key=f"toggle_{corpus['key']}",
        )
        st.session_state[mode_key] = "reasoning" if reasoning_on else "strict"
    with mode_col2:
        active_prompt = REASONING_SYSTEM_PROMPT if reasoning_on else SYSTEM_PROMPT
        mode_label = "Reasoning Mode" if reasoning_on else "Strict Grounding"
        st.markdown(
            f"""
            <div style="font-size:0.72rem;color:#64748b;margin-top:10px;line-height:1.5;">
            Active: <b style="color:#21918c;">{mode_label}</b>
            </div>
            """,
            unsafe_allow_html=True,
        )

    with st.expander(f"View system prompt — {mode_label}"):
        st.markdown(
            f"""
            <div style="max-height:350px;overflow-y:auto;overflow-x:hidden;
                 white-space:pre-wrap;word-wrap:break-word;font-family:monospace;
                 font-size:0.8rem;line-height:1.5;background:#f8f9fa;border:1px solid #e5e5e5;
                 border-radius:8px;padding:14px;color:#1a1a1a;">
            {active_prompt.format(corpus_label=corpus["label"])}
            </div>
            """,
            unsafe_allow_html=True,
        )

    if st.session_state[history_key]:
        if st.button("Clear conversation", key=f"clear_{corpus['key']}"):
            st.session_state[history_key] = []
            st.session_state[summary_key] = ""
            st.rerun()

    for turn in st.session_state[history_key]:
        with st.chat_message("user", avatar=svg_data_uri("user")):
            st.write(turn["question"])
        with st.chat_message("assistant", avatar=svg_data_uri("bot")):
            st.markdown(
                f"""
                <div class="bento-card" style="margin-top:4px;">
                  <div class="bento-desc" style="font-size:0.95rem;color:#1a1a1a;line-height:1.7;">{turn["answer"]}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )
            st.caption(
                f"Retrieval: {turn['retrieval_ms']:.0f} ms · Generation: {turn['generation_ms']:.0f} ms "
                f"· Model: {CLAUDE_MODEL}"
            )
            with st.expander("Retrieved sources"):
                for row in turn["chunks"].itertuples():
                    st.markdown(
                        f"""
                        <div class="bento-card" style="margin-bottom:8px;">
                          <span class="story-pill">{row.source_file}</span>
                          <span style="font-size:0.75rem;color:#94a3b8;margin-left:8px;">similarity {row.similarity:.2f}</span>
                          <div style="font-size:0.8rem;color:#475569;margin-top:8px;line-height:1.6;">{row.text[:400]}{"..." if len(row.text) > 400 else ""}</div>
                        </div>
                        """,
                        unsafe_allow_html=True,
                    )

    st.markdown(
        f"""
        <div style="font-size:0.72rem;color:#64748b;margin:14px 0 6px;line-height:1.5;">
        Start simply by asking Claude "What can I ask?" or expand the example
        questions below.
        <br>Conversational memory: sliding window of {MAX_HISTORY_TURNS} turns + compaction
        <span class="fn-wrap"><span class="info-mark">i</span><span class="fn-tooltip">
        Last {MAX_HISTORY_TURNS} turns are kept verbatim. Older turns are compacted into a
        running summary via a small extra Haiku call, instead of being dropped — this
        simulates the context/cost management a higher-traffic deployment would need,
        not something this corpus size actually requires.
        </span></span>
        </div>
        """,
        unsafe_allow_html=True,
    )

    sample_key = f"sample_select_{corpus['key']}"
    selected_sample = st.selectbox(
        "Example questions",
        options=["Choose an example question..."] + SAMPLE_QUESTIONS.get(corpus["key"], []),
        key=sample_key,
        label_visibility="collapsed",
    )

    question = st.chat_input(
        f"Ask a question about {corpus['label']}",
        key=f"chat_{corpus['key']}",
    )
    if selected_sample != "Choose an example question..." and st.session_state.get(f"{sample_key}_prev") != selected_sample:
        st.session_state[f"{sample_key}_prev"] = selected_sample
        question = selected_sample

    if question:
        with st.spinner("Retrieving relevant passages..."):
            t0 = time.perf_counter()
            top_chunks = retrieve_trips(question) if is_chromadb else retrieve(question, corpus_df, corpus_matrix)
            retrieval_ms = (time.perf_counter() - t0) * 1000

        with st.spinner("Generating answer..."):
            t0 = time.perf_counter()
            answer, updated_summary = ask_claude(
                question, top_chunks, corpus["label"],
                history=st.session_state[history_key],
                summary=st.session_state[summary_key],
                mode=st.session_state[mode_key],
            )
            generation_ms = (time.perf_counter() - t0) * 1000

        st.session_state[summary_key] = updated_summary
        st.session_state[history_key].append({
            "question": question,
            "answer": answer,
            "chunks": top_chunks,
            "retrieval_ms": retrieval_ms,
            "generation_ms": generation_ms,
        })
        st.rerun()

    st.markdown(
        """
        <div style="background:rgba(33,145,140,0.07);border-radius:12px;
             padding:16px 20px;margin-top:28px;">
          <div style="font-size:0.72rem;font-weight:700;color:#21918c;text-transform:uppercase;
               letter-spacing:0.5px;margin-bottom:6px;">Next steps</div>
          <div style="font-size:0.85rem;color:#475569;line-height:1.6;">
            <b>Agentic RAG</b> — try the "Agentic RAG" tab above: instead of picking the
            corpus via the stepper here, Claude picks it for you via real tool-use routing.
            <br><b>MCP (Model Context Protocol)</b> — expose this project's data fetchers
            (GCS, BigQuery, Vertex AI) as standardized MCP servers, reusable by any compatible
            client instead of custom Python glue per app.
          </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def _render_agentic_tab():
    history_key = "history_agentic"
    summary_key = "summary_agentic"
    if history_key not in st.session_state:
        st.session_state[history_key] = []
    if summary_key not in st.session_state:
        st.session_state[summary_key] = ""

    st.markdown(
        f"""
        <div style="font-size:0.72rem;color:#64748b;margin:4px 0 10px;line-height:1.5;">
        Claude picks which corpus to query based on your question — no tab to select.
        <span class="fn-wrap"><span class="info-mark">i</span><span class="fn-tooltip">
        Real tool-use routing: Claude is given one retrieval tool per corpus (Project Docs,
        The Pienza Papers, Trip Records) and calls exactly one per question based on what's
        likely relevant — the badge on each answer shows which corpus was actually queried.
        Conversational memory works the same way as Manual Retrieval: sliding window of
        {MAX_HISTORY_TURNS} turns + compaction.
        </span></span>
        </div>
        """,
        unsafe_allow_html=True,
    )

    if st.session_state[history_key]:
        if st.button("Clear conversation", key="clear_agentic"):
            st.session_state[history_key] = []
            st.session_state[summary_key] = ""
            st.rerun()

    for turn in st.session_state[history_key]:
        with st.chat_message("user", avatar=svg_data_uri("user")):
            st.write(turn["question"])
        with st.chat_message("assistant", avatar=svg_data_uri("bot")):
            if turn["corpus_label"]:
                st.markdown(
                    f'<span class="story-pill">Queried: {turn["corpus_label"]}</span>',
                    unsafe_allow_html=True,
                )
            st.markdown(
                f"""
                <div class="bento-card" style="margin-top:4px;">
                  <div class="bento-desc" style="font-size:0.95rem;color:#1a1a1a;line-height:1.7;">{turn["answer"]}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )
            st.caption(f"Total: {turn['total_ms']:.0f} ms · Model: {CLAUDE_MODEL}")
            if not turn["chunks"].empty:
                with st.expander("Retrieved sources"):
                    for row in turn["chunks"].itertuples():
                        st.markdown(
                            f"""
                            <div class="bento-card" style="margin-bottom:8px;">
                              <span class="story-pill">{row.source_file}</span>
                              <span style="font-size:0.75rem;color:#94a3b8;margin-left:8px;">similarity {row.similarity:.2f}</span>
                              <div style="font-size:0.8rem;color:#475569;margin-top:8px;line-height:1.6;">{row.text[:400]}{"..." if len(row.text) > 400 else ""}</div>
                            </div>
                            """,
                            unsafe_allow_html=True,
                        )

    question = st.chat_input("Ask anything — Claude will pick the right corpus", key="chat_agentic")

    if question:
        with st.spinner("Routing and retrieving..."):
            t0 = time.perf_counter()
            answer, updated_summary, corpus_label, chunks = ask_claude_agentic(
                question,
                history=st.session_state[history_key],
                summary=st.session_state[summary_key],
            )
            total_ms = (time.perf_counter() - t0) * 1000

        st.session_state[summary_key] = updated_summary
        st.session_state[history_key].append({
            "question": question,
            "answer": answer,
            "chunks": chunks,
            "corpus_label": corpus_label,
            "total_ms": total_ms,
        })
        st.rerun()


def _render_eval_tab():
    st.markdown(
        """
        <p style='font-size:14px;font-weight:400;color:#475569;line-height:1.7;margin-bottom:8px;'>
        Offline evaluation harness for RAG #1 (Project Docs corpus): a 24-question golden
        dataset, measured against a fixed baseline before each incremental retrieval
        upgrade — query rewriting, hybrid search, reranking — is adopted or rejected.
        This tab is <b>read-only</b>: it displays a precomputed comparison, it never runs
        an eval live. Full write-up: <code>.claude/claude_docs/rag_eval_workflow.md</code>.
        </p>
        """,
        unsafe_allow_html=True,
    )

    try:
        data = load_eval_comparison()
    except Exception:
        st.markdown(
            """
            <div style='border-left:6px solid #ffe600;background:#ffff00;border-radius:0 8px 8px 0;
                 padding:12px 16px;margin-top:10px;font-size:0.80rem;color:#1a1a1a;line-height:1.65;'>
              <span style='font-size:0.7rem;font-weight:900;text-transform:uppercase;letter-spacing:0.8px;
                    color:#cc6600;'>⚠ PENDING FIX — Comparison not found</span><br><br>
              Could not load <code>rag_eval_comparison.json</code> from GCS. Run
              <code>rag_eval_compare.py</code> and upload it via <code>gcs_deploy.py</code>.
            </div>
            """,
            unsafe_allow_html=True,
        )
        return

    st.markdown("#### Corpus build cost <span class=\"fn-wrap\"><span class=\"info-mark\">i</span>"
                "<span class=\"fn-tooltip\">Offline, already paid, historical — the one-time cost "
                "of embedding each corpus into the vector store. Not repeated per user question."
                "</span></span>", unsafe_allow_html=True)
    build_rows = [r for r in data["corpus_build_cost"] if r["corpus_key"] != "TOTAL"]
    total_row = next((r for r in data["corpus_build_cost"] if r["corpus_key"] == "TOTAL"), None)
    cols = st.columns(len(build_rows))
    for col, row in zip(cols, build_rows):
        with col:
            st.markdown(
                f"""
                <div class="bento-card">
                  <div class="bento-title">{row['corpus_label']}</div>
                  <div class="bento-value">${row['build_cost_usd']:.6f}</div>
                  <div class="bento-desc">{row['tokens']:,} tokens</div>
                </div>
                """,
                unsafe_allow_html=True,
            )
    if total_row:
        st.markdown(
            f"<div style='font-size:0.75rem;color:#64748b;margin-top:8px;'>"
            f"Total corpus build cost: <b>${total_row['build_cost_usd']:.6f}</b> "
            f"({total_row['tokens']:,} tokens)</div>",
            unsafe_allow_html=True,
        )

    st.markdown(
        "#### Retrieval config comparison <span class=\"fn-wrap\"><span class=\"info-mark\">i</span>"
        "<span class=\"fn-tooltip\">Context precision/recall use a single verified ground-truth "
        "chunk per question (not a multi-passage relevance set) — recall = hit (0/1), "
        "precision = 1/rank if hit. Embed cost is paid to GCP (Vertex AI); generation and "
        "judge cost are paid to Anthropic — three separate cost layers, never blended."
        "</span></span>",
        unsafe_allow_html=True,
    )
    rows = data["config_comparison"]
    table_df = pd.DataFrame([{
        "Config": r["config"],
        "Hit-rate": f"{r['hit_rate']:.1%}" if r["hit_rate"] is not None else "—",
        "Precision": f"{r['context_precision']:.3f}" if r["context_precision"] is not None else "—",
        "Recall": f"{r['context_recall']:.3f}" if r["context_recall"] is not None else "—",
        "Faithfulness": f"{r['faithfulness']:.2f}/5" if r["faithfulness"] is not None else "—",
        "Latency (ms)": f"{r['mean_latency_ms']:.0f}" if r["mean_latency_ms"] is not None else "—",
        "Embed $ (GCP)": f"${r['embed_cost_usd']:.6f}" if r["embed_cost_usd"] is not None else "—",
        "Generation $ (Anthropic)": f"${r['generation_cost_usd']:.6f}" if r["generation_cost_usd"] is not None else "—",
        "Judge $ (Anthropic)": f"${r['judge_cost_usd']:.6f}" if r["judge_cost_usd"] is not None else "—",
    } for r in rows])
    st.dataframe(table_df, hide_index=True, use_container_width=True)

    for r in rows:
        st.markdown(
            f"<div style='font-size:0.75rem;color:#334155;margin:4px 0;padding:8px 12px;"
            f"background:rgba(33,145,140,0.07);border-radius:0 8px 8px 0;border-left:4px solid #21918c;'>"
            f"<b>{r['config']}</b> — {r['adoption_note']}</div>",
            unsafe_allow_html=True,
        )

    per_corpus = data.get("per_corpus_comparison")
    if per_corpus:
        st.markdown(
            "#### Per-corpus breakdown <span class=\"fn-wrap\"><span class=\"info-mark\">i</span>"
            "<span class=\"fn-tooltip\">The overall row above blends all 4 corpora — a corpus with "
            "a real retrieval gap (e.g. The Pienza Papers) can hide behind 3 corpora that hit 100%. "
            "Pick a corpus to see its own numbers per config, 6 questions each.</span></span>",
            unsafe_allow_html=True,
        )
        corpus_labels = {c["key"]: c["label"] for c in CORPORA}
        available_keys = sorted({k for cfg in per_corpus.values() for k in cfg})
        selected_corpus = st.selectbox(
            "Corpus",
            options=available_keys,
            format_func=lambda k: corpus_labels.get(k, k),
            key="eval_corpus_select",
        )
        corpus_rows = []
        for r in rows:
            cfg = r["config"]
            pc = per_corpus.get(cfg, {}).get(selected_corpus, {})
            corpus_rows.append({
                "Config": cfg,
                "Hit-rate": f"{pc['hit_rate']:.1%}" if pc.get("hit_rate") is not None else "—",
                "Precision": f"{pc['context_precision']:.3f}" if pc.get("context_precision") is not None else "—",
                "Recall": f"{pc['context_recall']:.3f}" if pc.get("context_recall") is not None else "—",
                "Faithfulness": f"{pc['faithfulness']:.2f}/5" if pc.get("faithfulness") is not None else "—",
                "Latency (ms)": f"{pc['mean_latency_ms']:.0f}" if pc.get("mean_latency_ms") is not None else "—",
                "Embed $ (GCP)": f"${pc['embed_cost_usd']:.6f}" if pc.get("embed_cost_usd") is not None else "—",
                "Generation $ (Anthropic)": f"${pc['generation_cost_usd']:.6f}" if pc.get("generation_cost_usd") is not None else "—",
                "Judge $ (Anthropic)": f"${pc['judge_cost_usd']:.6f}" if pc.get("judge_cost_usd") is not None else "—",
            })
        st.dataframe(pd.DataFrame(corpus_rows), hide_index=True, use_container_width=True)

    followup = data.get("followup_comparison")
    if followup:
        st.markdown(
            "#### Query rewriting — follow-up pairs (the scenario it's designed to fix)",
            unsafe_allow_html=True,
        )
        fcol1, fcol2 = st.columns(2)
        with fcol1:
            st.markdown(
                f"""
                <div class="bento-card">
                  <div class="bento-title">Raw follow-up (no rewrite)</div>
                  <div class="bento-value">{followup['raw_hit_rate']:.0%}</div>
                  <div class="bento-desc">hit-rate on {followup['n_pairs']} pronoun/reference-ambiguous pairs</div>
                </div>
                """,
                unsafe_allow_html=True,
            )
        with fcol2:
            st.markdown(
                f"""
                <div class="bento-card">
                  <div class="bento-title">Rewritten follow-up</div>
                  <div class="bento-value">{followup['rewritten_hit_rate']:.0%}</div>
                  <div class="bento-desc">hit-rate after rewrite_query() resolves the reference</div>
                </div>
                """,
                unsafe_allow_html=True,
            )


_outer_tabs = st.tabs(["Manual Retrieval", "Agentic RAG", "RAG Eval"])

with _outer_tabs[0]:
    _render_stepper()
    _corpus_tabs = st.tabs([c["label"] for c in CORPORA])
    for _tab, _corpus in zip(_corpus_tabs, CORPORA):
        with _tab:
            _render_corpus_tab(_corpus)

with _outer_tabs[1]:
    _render_agentic_tab()

with _outer_tabs[2]:
    _render_eval_tab()
