import time

import streamlit as st

from components.sidebar import build_sidebar
from components.styles import GLOBAL_CSS
from config import FAVICON, build_page_title
from pages._0010_data import (
    CORPORA, CLAUDE_MODEL, MAX_HISTORY_TURNS, load_corpus, retrieve,
    load_trip_collection, retrieve_trips, ask_claude, ask_claude_agentic,
    format_token_count,
)

# ==========================================
# PAGE CONFIGURATION
# ==========================================
st.set_page_config(page_title=build_page_title("RAG Assistant"), page_icon=FAVICON, layout="wide")

build_sidebar()
st.markdown(GLOBAL_CSS, unsafe_allow_html=True)
st.markdown("<style></style>", unsafe_allow_html=True)

st.markdown("# RAG Assistant")
st.markdown(
    "<h4 style='font-weight:300; color:#21918c; font-size:19px; margin:-10px 0 20px;'>"
    "Retrieval-Augmented Generation over Pienza's own project documentation</h4>",
    unsafe_allow_html=True,
)
st.markdown(
    """
    <p style='font-size:14px;font-weight:400;color:#475569;line-height:1.7;margin-bottom:16px;'>
    Ask a question about how this project works. Answers are generated by Claude, grounded only
    in passages retrieved via Vertex AI (<code>text-embedding-004</code>) embeddings. Pick the
    corpus yourself under <b>Manual Retrieval</b>, or let Claude pick it via tool-use routing
    under <b>Agentic RAG</b>.
    </p>
    """,
    unsafe_allow_html=True,
)

def _render_stepper():
    """Corpus selector — horizontal stepper (same visual pattern as 0008's
    ci-stepper), driving hidden st.tabs. Only relevant to Manual Retrieval —
    Agentic RAG has no stepper, the model picks the corpus itself. More
    corpora append to CORPORA in _0010_data.py, not to this markup."""
    st.markdown(
        """
<style>
.corpus-stepper { display:flex; align-items:flex-start; gap:0; margin:18px 0 6px 0; }
.corpus-step {
  display:flex; flex-direction:column; align-items:center; flex:1;
  position:relative; cursor:pointer;
}
.corpus-step:not(:last-child)::after {
  content:''; position:absolute; top:14px; left:calc(50% + 14px);
  width:calc(100% - 28px); height:2px; background:rgba(33,145,140,0.2); z-index:0;
}
.corpus-dot {
  width:28px; height:28px; border-radius:50%;
  background:rgba(33,145,140,0.12); border:1.5px solid rgba(33,145,140,0.4);
  display:flex; align-items:center; justify-content:center;
  font-size:0.60rem; font-weight:700; color:#21918c;
  z-index:1; position:relative; flex-shrink:0;
  transition: background 0.15s, border-color 0.15s;
}
.corpus-step:hover .corpus-dot { background:rgba(33,145,140,0.22); border-color:#21918c; }
.corpus-step-label {
  font-size:0.68rem; font-weight:600; color:#334155;
  text-align:center; margin-top:6px; line-height:1.3;
}
.corpus-step-sub {
  font-size:0.60rem; color:#64748b;
  text-align:center; margin-top:2px; line-height:1.3;
}
.corpus-step-tokens {
  font-size:0.58rem; color:#94a3b8;
  text-align:center; margin-top:1px; line-height:1.3;
}
.corpus-step:hover .corpus-step-label { color:#21918c; }
.corpus-step.corpus-active .corpus-dot {
  background:#21918c !important; border-color:#21918c !important; color:#fff !important;
}
.corpus-step.corpus-active .corpus-step-label { color:#21918c !important; font-weight:700; }
</style>
""" + "<div class=\"corpus-stepper\">" + "".join(
    f'<div class="corpus-step{" corpus-active" if i == 0 else ""}">'
    f'<div class="corpus-dot">C{i+1}</div>'
    f'<div class="corpus-step-label">{c["label"]}</div>'
    f'<div class="corpus-step-sub">{c["sub"]}</div>'
    f'<div class="corpus-step-tokens">{format_token_count(c["tokens"])}</div>'
    f'</div>'
    for i, c in enumerate(CORPORA)
) + "</div>", unsafe_allow_html=True)

    st.markdown(
        """
<style>
[data-baseweb="tab-panel"] [data-baseweb="tab-list"] { display:none !important; }
[data-baseweb="tab-panel"] [data-baseweb="tab-border"] { display:none !important; }
</style>
""",
        unsafe_allow_html=True,
    )

    st.components.v1.html(
        """
<script>
setTimeout(function() {
  var stepperDiv = window.parent.document.querySelector('.corpus-stepper');
  var scope = (stepperDiv && stepperDiv.closest('[data-baseweb="tab-panel"]')) || window.parent.document;
  var steps = scope.querySelectorAll('.corpus-step');
  var allTabs = scope.querySelectorAll('[data-baseweb="tab"]');

  function setActive(idx) {
    steps.forEach(function(s) { s.classList.remove('corpus-active'); });
    if (steps[idx]) steps[idx].classList.add('corpus-active');
  }

  var initIdx = 0;
  for (var j = 0; j < allTabs.length; j++) {
    if (allTabs[j].getAttribute('aria-selected') === 'true') { initIdx = j; break; }
  }
  setActive(initIdx);

  steps.forEach(function(step, i) {
    step.addEventListener('click', function() {
      var target = allTabs[i];
      if (target) {
        var sy = window.parent.scrollY;
        target.click();
        setActive(i);
        setTimeout(function() { window.parent.scrollTo(0, sy); }, 50);
        setTimeout(function() { window.parent.scrollTo(0, sy); }, 300);
      }
    });
  });
}, 300);
</script>
""",
        height=0,
    )


def _render_corpus_tab(corpus: dict):
    is_chromadb = corpus.get("kind") == "chromadb"

    if is_chromadb:
        collection = load_trip_collection()
        corpus_empty = collection.count() == 0
        missing_hint = "the ChromaDB store under gcs://pienza-streamlit/chroma_trips/"
    else:
        corpus_df, corpus_matrix = load_corpus(corpus["file"])
        corpus_empty = corpus_df is None or corpus_df.empty
        missing_hint = f"<code>{corpus['file']}</code>"

    if corpus_empty:
        st.markdown(
            f"""
            <div style='border-left:6px solid #ffe600;background:#ffff00;border-radius:0 8px 8px 0;
                 padding:12px 16px;margin-top:10px;font-size:0.80rem;color:#1a1a1a;line-height:1.65;'>
              <span style='font-size:0.7rem;font-weight:900;text-transform:uppercase;letter-spacing:0.8px;
                    color:#cc6600;'>⚠ PENDING FIX — Corpus not found</span><br><br>
              Could not load {missing_hint} from GCS. Confirm the file was
              uploaded to bucket <code>pienza-streamlit</code>.
            </div>
            """,
            unsafe_allow_html=True,
        )
        return

    history_key = f"history_{corpus['key']}"
    summary_key = f"summary_{corpus['key']}"
    if history_key not in st.session_state:
        st.session_state[history_key] = []
    if summary_key not in st.session_state:
        st.session_state[summary_key] = ""

    st.markdown(
        f"""
        <div style="font-size:0.72rem;color:#64748b;margin:4px 0 10px;line-height:1.5;">
        Conversational memory: sliding window of {MAX_HISTORY_TURNS} turns + compaction
        <span class="fn-wrap"><span class="info-mark">i</span><span class="fn-tooltip">
        Last {MAX_HISTORY_TURNS} turns are kept verbatim. Older turns are compacted into a
        running summary via a small extra Haiku call, instead of being dropped — this
        simulates the context/cost management a higher-traffic deployment would need,
        not something this corpus size actually requires.
        </span></span>
        </div>
        """,
        unsafe_allow_html=True,
    )

    if st.session_state[history_key]:
        if st.button("Clear conversation", key=f"clear_{corpus['key']}"):
            st.session_state[history_key] = []
            st.session_state[summary_key] = ""
            st.rerun()

    for turn in st.session_state[history_key]:
        with st.chat_message("user"):
            st.write(turn["question"])
        with st.chat_message("assistant"):
            st.markdown(
                f"""
                <div class="bento-card" style="margin-top:4px;">
                  <div class="bento-desc" style="font-size:0.95rem;color:#1a1a1a;line-height:1.7;">{turn["answer"]}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )
            st.caption(
                f"Retrieval: {turn['retrieval_ms']:.0f} ms · Generation: {turn['generation_ms']:.0f} ms "
                f"· Model: {CLAUDE_MODEL}"
            )
            with st.expander("Retrieved sources"):
                for row in turn["chunks"].itertuples():
                    st.markdown(
                        f"""
                        <div class="bento-card" style="margin-bottom:8px;">
                          <span class="story-pill">{row.source_file}</span>
                          <span style="font-size:0.75rem;color:#94a3b8;margin-left:8px;">similarity {row.similarity:.2f}</span>
                          <div style="font-size:0.8rem;color:#475569;margin-top:8px;line-height:1.6;">{row.text[:400]}{"..." if len(row.text) > 400 else ""}</div>
                        </div>
                        """,
                        unsafe_allow_html=True,
                    )

    question = st.chat_input(
        f"Ask a question about {corpus['label']}",
        key=f"chat_{corpus['key']}",
    )

    if question:
        with st.spinner("Retrieving relevant passages..."):
            t0 = time.perf_counter()
            top_chunks = retrieve_trips(question) if is_chromadb else retrieve(question, corpus_df, corpus_matrix)
            retrieval_ms = (time.perf_counter() - t0) * 1000

        with st.spinner("Generating answer..."):
            t0 = time.perf_counter()
            answer, updated_summary = ask_claude(
                question, top_chunks, corpus["label"],
                history=st.session_state[history_key],
                summary=st.session_state[summary_key],
            )
            generation_ms = (time.perf_counter() - t0) * 1000

        st.session_state[summary_key] = updated_summary
        st.session_state[history_key].append({
            "question": question,
            "answer": answer,
            "chunks": top_chunks,
            "retrieval_ms": retrieval_ms,
            "generation_ms": generation_ms,
        })
        st.rerun()

    st.markdown(
        """
        <div style="background:rgba(33,145,140,0.07);border-radius:12px;
             padding:16px 20px;margin-top:28px;">
          <div style="font-size:0.72rem;font-weight:700;color:#21918c;text-transform:uppercase;
               letter-spacing:0.5px;margin-bottom:6px;">Next steps</div>
          <div style="font-size:0.85rem;color:#475569;line-height:1.6;">
            <b>Agentic RAG</b> — try the "Agentic RAG" tab above: instead of picking the
            corpus via the stepper here, Claude picks it for you via real tool-use routing.
            <br><b>MCP (Model Context Protocol)</b> — expose this project's data fetchers
            (GCS, BigQuery, Vertex AI) as standardized MCP servers, reusable by any compatible
            client instead of custom Python glue per app.
          </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def _render_agentic_tab():
    history_key = "history_agentic"
    summary_key = "summary_agentic"
    if history_key not in st.session_state:
        st.session_state[history_key] = []
    if summary_key not in st.session_state:
        st.session_state[summary_key] = ""

    st.markdown(
        f"""
        <div style="font-size:0.72rem;color:#64748b;margin:4px 0 10px;line-height:1.5;">
        Claude picks which corpus to query based on your question — no tab to select.
        <span class="fn-wrap"><span class="info-mark">i</span><span class="fn-tooltip">
        Real tool-use routing: Claude is given one retrieval tool per corpus (Project Docs,
        The Pienza Papers, Trip Records) and calls exactly one per question based on what's
        likely relevant — the badge on each answer shows which corpus was actually queried.
        Conversational memory works the same way as Manual Retrieval: sliding window of
        {MAX_HISTORY_TURNS} turns + compaction.
        </span></span>
        </div>
        """,
        unsafe_allow_html=True,
    )

    if st.session_state[history_key]:
        if st.button("Clear conversation", key="clear_agentic"):
            st.session_state[history_key] = []
            st.session_state[summary_key] = ""
            st.rerun()

    for turn in st.session_state[history_key]:
        with st.chat_message("user"):
            st.write(turn["question"])
        with st.chat_message("assistant"):
            if turn["corpus_label"]:
                st.markdown(
                    f'<span class="story-pill">Queried: {turn["corpus_label"]}</span>',
                    unsafe_allow_html=True,
                )
            st.markdown(
                f"""
                <div class="bento-card" style="margin-top:4px;">
                  <div class="bento-desc" style="font-size:0.95rem;color:#1a1a1a;line-height:1.7;">{turn["answer"]}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )
            st.caption(f"Total: {turn['total_ms']:.0f} ms · Model: {CLAUDE_MODEL}")
            if not turn["chunks"].empty:
                with st.expander("Retrieved sources"):
                    for row in turn["chunks"].itertuples():
                        st.markdown(
                            f"""
                            <div class="bento-card" style="margin-bottom:8px;">
                              <span class="story-pill">{row.source_file}</span>
                              <span style="font-size:0.75rem;color:#94a3b8;margin-left:8px;">similarity {row.similarity:.2f}</span>
                              <div style="font-size:0.8rem;color:#475569;margin-top:8px;line-height:1.6;">{row.text[:400]}{"..." if len(row.text) > 400 else ""}</div>
                            </div>
                            """,
                            unsafe_allow_html=True,
                        )

    question = st.chat_input("Ask anything — Claude will pick the right corpus", key="chat_agentic")

    if question:
        with st.spinner("Routing and retrieving..."):
            t0 = time.perf_counter()
            answer, updated_summary, corpus_label, chunks = ask_claude_agentic(
                question,
                history=st.session_state[history_key],
                summary=st.session_state[summary_key],
            )
            total_ms = (time.perf_counter() - t0) * 1000

        st.session_state[summary_key] = updated_summary
        st.session_state[history_key].append({
            "question": question,
            "answer": answer,
            "chunks": chunks,
            "corpus_label": corpus_label,
            "total_ms": total_ms,
        })
        st.rerun()


_outer_tabs = st.tabs(["Manual Retrieval", "Agentic RAG"])

with _outer_tabs[0]:
    _render_stepper()
    _corpus_tabs = st.tabs([c["label"] for c in CORPORA])
    for _tab, _corpus in zip(_corpus_tabs, CORPORA):
        with _tab:
            _render_corpus_tab(_corpus)

with _outer_tabs[1]:
    _render_agentic_tab()
