"""Data literals and pure helpers used by 0002_Acquisition_Pipelines.py (Layer 1 extraction)."""

import base64
import io
import re
from pathlib import Path

import streamlit as st
from PIL import Image

from utils.gcp_client import fetch_bytes_from_gcs


@st.cache_data(show_spinner=False)
def img_b64(img_path: str, max_width: int = 320) -> str:
    """Fetches an OCR screenshot from GCS, downsizes it, and returns a base64 JPEG string."""
    raw = fetch_bytes_from_gcs("pienza-streamlit", img_path)
    img = Image.open(io.BytesIO(raw)).convert("RGB")
    if img.width > max_width:
        h = int(img.height * max_width / img.width)
        img = img.resize((max_width, h), Image.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=82, optimize=True)
    return base64.b64encode(buf.getvalue()).decode()


# Hardcoded 2026-07-09 — see project_live_calls_audit / project_tech_debt memory.
# Frozen ground truth for the 10 Engine 2 carousel offers (never changes; this
# IS the dataset, not a query result that could drift). Sensitive fields
# (upfront_fare, pickup/dropoff_address, image_content_hash, lat/lon) are
# pre-masked with the same obf_* functions used elsewhere on this page —
# the obfuscation functions are idempotent, so any downstream re-application
# is a safe no-op. Regenerate by re-running the 3 batched BQ queries this
# replaced if the underlying offers/raw_offers_ocr/silver_palette rows ever change.

_DF_OCR_RECORDS = [{'ocr_id': 'OCR01714',
  'image_filename': 'IMG_9277.PNG',
  'time_taken': '2:47 PM',
  'ride_type': 'Black Exclusivo',
  'upfront_fare': '$###.##',
  'pickup_details': '7 min (1.7 km)',
  'pickup_address': 'Calle Montes Urales, Lomas de Chapultepec',
  'trip_details': '27 min (8.9 km)',
  'dropoff_address': 'Privada Tamarindos ####, Granjas Palo Alto, 05120 Cuajimalpa de Morelos - Bosques de las lomas',
  'rider_rating': '4.70 (622 ratings)',
  'special_note': '+$8.00 incluido'},
 {'ocr_id': 'OCR03289',
  'image_filename': 'IMG_2793.PNG',
  'time_taken': '6:33',
  'ride_type': 'Comfort',
  'upfront_fare': '##.#',
  'pickup_details': '5 min (2.9 km)',
  'pickup_address': 'Av Tamaulipas, Santa Fe',
  'trip_details': '4 min (2.3 km)',
  'dropoff_address': 'Prol Paseo de Reforma ####, Álvaro Obregón, 01219 Álvaro Obregón - Santa Fe',
  'rider_rating': '4.82 (789)',
  'special_note': 'Exclusivo, +$18.00 incluido, Turbo+ de $9.44 incluido'},
 {'ocr_id': 'OCR03573',
  'image_filename': 'IMG_3428.PNG',
  'time_taken': '7:21',
  'ride_type': 'Turbo+',
  'upfront_fare': '###.##',
  'pickup_details': '10 min (4.1 km)',
  'pickup_address': 'Primer Retorno de Cumbres de Acultzingo, Bosques',
  'trip_details': '16 min (6.0 km)',
  'dropoff_address': 'Bondojito ####, Col Las Américas, 01120 Álvaro Obregón - Observatorio',
  'rider_rating': '4.80 (330)',
  'special_note': 'Identidad verificada, Turbo+ de $15.36 incluido'},
 {'ocr_id': 'OCR03692',
  'image_filename': 'IMG_3679.PNG',
  'time_taken': '15:37',
  'ride_type': 'UberX',
  'upfront_fare': '###.##',
  'pickup_details': '13 min (13.4 km)',
  'pickup_address': 'Calle Vía Magna, Interlomas',
  'trip_details': '13 min (3.5 km)',
  'dropoff_address': 'Av Universidad Anáhuac ####, Col Lomas Anáhuac Huixquilucan, 52786 Huixquilucan, México - '
                     'Bosques',
  'rider_rating': '4.89 (751)',
  'special_note': '+$14.00 incluido,Identidad verificada'},
 {'ocr_id': 'OCR03982',
  'image_filename': 'IMG_4346.PNG',
  'time_taken': '19:13',
  'ride_type': 'UberX',
  'upfront_fare': '###.##',
  'pickup_details': '24 min (2.9 km)',
  'pickup_address': 'Avenida General Pedro Antonio de los Santos, Condesa / Roma',
  'trip_details': '50 min (9.3 km)',
  'dropoff_address': 'Prol. P.º de la Reforma ####, Santa Fe, Zedec Sta Fé, Álvaro Obregón, 01310 Ciudad de México, '
                     'CDMX, México - Santa Fe',
  'rider_rating': '4.69 (629)',
  'special_note': '+$12.00 incluido, Turbo+ de $55.37 incluido, VIP'},
 {'ocr_id': 'OCR01600',
  'image_filename': 'IMG_9029.PNG',
  'time_taken': '5:53',
  'ride_type': 'UberX (Exclusivo)',
  'upfront_fare': '$###.##',
  'pickup_details': '10 min (4.7 km)',
  'pickup_address': 'Calle Naranjo, Claveria - Azcapotzalco',
  'trip_details': '41 min (18.7 km)',
  'dropoff_address': 'Vialidad de la Barranca ####, Col. Ex Hacienda Jesús del Monte, Bosque de las Palmas, 52787 '
                     'Naucalpan de Juárez, Méx., México - Interlomas',
  'rider_rating': '4.79 (6888 ratings)',
  'special_note': 'VIP, +$30.00 incluido'},
 {'ocr_id': 'OCR00159',
  'image_filename': 'IMG_5813.PNG',
  'time_taken': '4:48',
  'ride_type': 'UberX Exclusivo',
  'upfront_fare': '$###.##',
  'pickup_details': '3 min (0.9 km)',
  'pickup_address': 'Calle Bosque de Amates, Bosques de las lomas',
  'trip_details': '44 min (8.5 km)',
  'dropoff_address': 'Av Insurgentes Tacubaya ####, Col Tacubaya Miguel Hidalgo, 11870 Ciudad de México, CMX - '
                     'Condesa / Roma',
  'rider_rating': '4.56 (764 ratings)',
  'special_note': 'A Turbo+ of $42.95 is included. The user is a VIP.'},
 {'ocr_id': 'OCR02768',
  'image_filename': 'IMG_1691.PNG',
  'time_taken': '15:32',
  'ride_type': 'Business Comfort',
  'upfront_fare': '###.##',
  'pickup_details': '8 min (1.7 km)',
  'pickup_address': 'Lomas de Chapultepec',
  'trip_details': '43 min (13.4 km)',
  'dropoff_address': 'Carlos Lazo ####, Col Santa Fe Tlayapaca Álvaro Obregón, 01389 Ciudad de México, Ciudad de '
                     'México - Santa Fe',
  'rider_rating': '4.78 (2118)',
  'special_note': 'Exclusivo, VIP'},
 {'ocr_id': 'OCR00535',
  'image_filename': 'IMG_6624.PNG',
  'time_taken': '8:57',
  'ride_type': 'UberX',
  'upfront_fare': '$###.##',
  'pickup_details': '13 min (4.7 km)',
  'pickup_address': 'Avenida Primero de Mayo, Nápoles',
  'trip_details': '41 min (7.1 km)',
  'dropoff_address': 'Av Paseo de las Palmas #### Torre Optima 1 PB, Miguel Hidalgo, Col Lomas de Chapultepec Miguel '
                     'Hidalgo, 11000 Ciudad de México, Ciudad de México - Lomas de Chapultepec',
  'rider_rating': '4.83 (2834 ratings)',
  'special_note': 'Identity verified.'},
 {'ocr_id': 'OCR02057',
  'image_filename': 'IMG_0038.PNG',
  'time_taken': '6:04 AM',
  'ride_type': 'UberX',
  'upfront_fare': '$###.##',
  'pickup_details': '10 min (3.7 km)',
  'pickup_address': 'Yucatán #### Loc E3 Piso 1er, Cuauhtémoc, Condesa / Roma',
  'trip_details': '19 min (12.7 km)',
  'dropoff_address': 'Av. Capitán Carlos León S/N, Peñón de los Baños, Venustiano Carranza, 15620 Ciudad de México, '
                     'CDMX, México - Aeropuerto Internacional Benito Juárez',
  'rider_rating': '5.00 (0 ratings)',
  'special_note': 'N/A'}]

_DF_OFFERS_RECORDS = [{'image_filename': 'IMG_6624.PNG',
  'offer_id': 'OF00535',
  'session_fk': 'SID0008',
  'image_content_hash': 'bf164a332e03...',
  'offer_timestamp': '2025-08-26 08:57:29',
  'upfront_fare': '###.#',
  'product_category': 'uberx',
  'time_to_pickup_sec': 780.0,
  'dist_to_pickup_km': 4.7,
  'est_trip_time_sec': 2460.0,
  'est_trip_dist_km': 7.1,
  'pickup_address': 'avenida primero de mayo, napoles, ciudad de mexico, cdmx, mexico',
  'dropoff_address': 'Av Paseo de las Palmas #### Torre Optima 1 PB, Miguel Hidalgo, Col Lomas de Chapultepec Miguel '
                     'Hidalgo, 11000 Ciudad de México, Ciudad de México - Lomas de Chapultepec',
  'pickup_lat': '19.39####',
  'pickup_lon': '-99.18####',
  'dropoff_lat': '19.43####',
  'dropoff_lon': '-99.21####',
  'is_surge': 0,
  'surge_amount': None,
  'is_turbo_plus': 0,
  'turbo_plus_amount': None,
  'is_reservation': 0,
  'reservation_amount': None,
  'is_priority': 0,
  'priority_amount': None,
  'is_exclusive': 0,
  'is_vip': 0,
  'is_identity_verified': 1,
  'is_long_trip': 0,
  'is_multiple_destinations': 0,
  'is_teens': 0,
  'rider_star_rating': 4.83,
  'rider_trip_count': 2834.0},
 {'image_filename': 'IMG_9277.PNG',
  'offer_id': 'OF01714',
  'session_fk': 'SID0025',
  'image_content_hash': 'bcb8ac7cdf89...',
  'offer_timestamp': '2025-09-04 14:47:02',
  'upfront_fare': '###.##',
  'product_category': 'black',
  'time_to_pickup_sec': 420.0,
  'dist_to_pickup_km': 1.7,
  'est_trip_time_sec': 1620.0,
  'est_trip_dist_km': 8.9,
  'pickup_address': 'calle montes urales, lomas de chapultepec',
  'dropoff_address': 'Privada Tamarindos ####, Granjas Palo Alto, 05120 Cuajimalpa de Morelos - Bosques de las lomas',
  'pickup_lat': '19.42####',
  'pickup_lon': '-99.20####',
  'dropoff_lat': '19.38####',
  'dropoff_lon': '-99.25####',
  'is_surge': 1,
  'surge_amount': 8.0,
  'is_turbo_plus': 0,
  'turbo_plus_amount': None,
  'is_reservation': 0,
  'reservation_amount': None,
  'is_priority': 0,
  'priority_amount': None,
  'is_exclusive': 1,
  'is_vip': 0,
  'is_identity_verified': 0,
  'is_long_trip': 0,
  'is_multiple_destinations': 0,
  'is_teens': 0,
  'rider_star_rating': 4.7,
  'rider_trip_count': 622.0},
 {'image_filename': 'IMG_0038.PNG',
  'offer_id': 'OF02057',
  'session_fk': 'SID0029',
  'image_content_hash': 'a0bb89ec351d...',
  'offer_timestamp': '2025-09-11 06:04:15',
  'upfront_fare': '###.##',
  'product_category': 'uberx',
  'time_to_pickup_sec': 600.0,
  'dist_to_pickup_km': 3.7,
  'est_trip_time_sec': 1140.0,
  'est_trip_dist_km': 12.7,
  'pickup_address': 'yucatan #### loc e3 piso 1er, cuauhtemoc, condesa / roma',
  'dropoff_address': 'Av. Capitán Carlos León S/N, Peñón de los Baños, Venustiano Carranza, 15620 Ciudad de México, '
                     'CDMX, México - Aeropuerto Internacional Benito Juárez',
  'pickup_lat': '19.41####',
  'pickup_lon': '-99.16####',
  'dropoff_lat': '19.43####',
  'dropoff_lon': '-99.08####',
  'is_surge': 0,
  'surge_amount': None,
  'is_turbo_plus': 0,
  'turbo_plus_amount': None,
  'is_reservation': 0,
  'reservation_amount': None,
  'is_priority': 0,
  'priority_amount': None,
  'is_exclusive': 0,
  'is_vip': 0,
  'is_identity_verified': 0,
  'is_long_trip': 0,
  'is_multiple_destinations': 0,
  'is_teens': 0,
  'rider_star_rating': 5.0,
  'rider_trip_count': 0.0},
 {'image_filename': 'IMG_2793.PNG',
  'offer_id': 'OF03289',
  'session_fk': 'SID0045',
  'image_content_hash': '8b6b99bc2f6a...',
  'offer_timestamp': '2025-09-22 06:33:23',
  'upfront_fare': '##.#',
  'product_category': 'comfort',
  'time_to_pickup_sec': 300.0,
  'dist_to_pickup_km': 2.9,
  'est_trip_time_sec': 240.0,
  'est_trip_dist_km': 2.3,
  'pickup_address': 'avenida tamaulipas, santa fe, ciudad de mexico, cdmx, mexico',
  'dropoff_address': 'Prol Paseo de Reforma ####, Álvaro Obregón, 01219 Álvaro Obregón - Santa Fe',
  'pickup_lat': '19.35####',
  'pickup_lon': '-99.26####',
  'dropoff_lat': '19.37####',
  'dropoff_lon': '-99.26####',
  'is_surge': 1,
  'surge_amount': 18.0,
  'is_turbo_plus': 1,
  'turbo_plus_amount': 9.44,
  'is_reservation': 0,
  'reservation_amount': None,
  'is_priority': 0,
  'priority_amount': None,
  'is_exclusive': 1,
  'is_vip': 0,
  'is_identity_verified': 0,
  'is_long_trip': 0,
  'is_multiple_destinations': 0,
  'is_teens': 0,
  'rider_star_rating': 4.82,
  'rider_trip_count': 789.0},
 {'image_filename': 'IMG_3428.PNG',
  'offer_id': 'OF03573',
  'session_fk': 'SID0047',
  'image_content_hash': '3e4e95f41ec9...',
  'offer_timestamp': '2025-09-23 07:21:04',
  'upfront_fare': '###.##',
  'product_category': 'black',
  'time_to_pickup_sec': 600.0,
  'dist_to_pickup_km': 4.1,
  'est_trip_time_sec': 960.0,
  'est_trip_dist_km': 6.0,
  'pickup_address': 'primer retorno de cumbres de acultzingo, bosques, ciudad de mexico, cdmx, mexico',
  'dropoff_address': 'Bondojito ####, Col Las Américas, 01120 Álvaro Obregón - Observatorio',
  'pickup_lat': '19.40####',
  'pickup_lon': '-99.22####',
  'dropoff_lat': '19.39####',
  'dropoff_lon': '-99.20####',
  'is_surge': 0,
  'surge_amount': None,
  'is_turbo_plus': 1,
  'turbo_plus_amount': 15.36,
  'is_reservation': 0,
  'reservation_amount': None,
  'is_priority': 0,
  'priority_amount': None,
  'is_exclusive': 0,
  'is_vip': 0,
  'is_identity_verified': 1,
  'is_long_trip': 0,
  'is_multiple_destinations': 0,
  'is_teens': 0,
  'rider_star_rating': 4.8,
  'rider_trip_count': 330.0},
 {'image_filename': 'IMG_3679.PNG',
  'offer_id': 'OF03692',
  'session_fk': 'SID0048',
  'image_content_hash': 'ab4a8bf4a5ca...',
  'offer_timestamp': '2025-09-23 15:37:37',
  'upfront_fare': '###.##',
  'product_category': 'uberx',
  'time_to_pickup_sec': 780.0,
  'dist_to_pickup_km': 13.4,
  'est_trip_time_sec': 780.0,
  'est_trip_dist_km': 3.5,
  'pickup_address': 'calle via magna, interlomas',
  'dropoff_address': 'Av Universidad Anáhuac ####, Col Lomas Anáhuac Huixquilucan, 52786 Huixquilucan, México - '
                     'Bosques',
  'pickup_lat': '19.40####',
  'pickup_lon': '-99.27####',
  'dropoff_lat': '19.40####',
  'dropoff_lon': '-99.26####',
  'is_surge': 1,
  'surge_amount': 14.0,
  'is_turbo_plus': 0,
  'turbo_plus_amount': None,
  'is_reservation': 0,
  'reservation_amount': None,
  'is_priority': 0,
  'priority_amount': None,
  'is_exclusive': 0,
  'is_vip': 0,
  'is_identity_verified': 1,
  'is_long_trip': 0,
  'is_multiple_destinations': 0,
  'is_teens': 0,
  'rider_star_rating': 4.89,
  'rider_trip_count': 751.0},
 {'image_filename': 'IMG_5813.PNG',
  'offer_id': 'OF00159',
  'session_fk': 'SID0003',
  'image_content_hash': '793dea9502b4...',
  'offer_timestamp': '2025-08-22 16:48:35',
  'upfront_fare': '###.#',
  'product_category': 'uberx',
  'time_to_pickup_sec': 180.0,
  'dist_to_pickup_km': 0.9,
  'est_trip_time_sec': 2640.0,
  'est_trip_dist_km': 8.5,
  'pickup_address': 'bosque de amates, bosques de las lomas',
  'dropoff_address': 'Av Insurgentes Tacubaya ####, Col Tacubaya Miguel Hidalgo, 11870 Ciudad de México, CMX - '
                     'Condesa / Roma',
  'pickup_lat': '19.39####',
  'pickup_lon': '-99.24####',
  'dropoff_lat': '19.40####',
  'dropoff_lon': '-99.18####',
  'is_surge': 1,
  'surge_amount': 4.0,
  'is_turbo_plus': 1,
  'turbo_plus_amount': 42.95,
  'is_reservation': 0,
  'reservation_amount': None,
  'is_priority': 0,
  'priority_amount': None,
  'is_exclusive': 1,
  'is_vip': 1,
  'is_identity_verified': 0,
  'is_long_trip': 0,
  'is_multiple_destinations': 0,
  'is_teens': 0,
  'rider_star_rating': 4.56,
  'rider_trip_count': 764.0},
 {'image_filename': 'IMG_9029.PNG',
  'offer_id': 'OF01600',
  'session_fk': 'SID0024',
  'image_content_hash': 'd2cfe46785bb...',
  'offer_timestamp': '2025-09-04 05:53:13',
  'upfront_fare': '###.##',
  'product_category': 'uberx',
  'time_to_pickup_sec': 600.0,
  'dist_to_pickup_km': 4.7,
  'est_trip_time_sec': 2460.0,
  'est_trip_dist_km': 18.7,
  'pickup_address': 'calle naranjo, claveria - azcapotzalco',
  'dropoff_address': 'Vialidad de la Barranca ####, Col. Ex Hacienda Jesús del Monte, Bosque de las Palmas, 52787 '
                     'Naucalpan de Juárez, Méx., México - Interlomas',
  'pickup_lat': '19.45####',
  'pickup_lon': '-99.15####',
  'dropoff_lat': '19.39####',
  'dropoff_lon': '-99.28####',
  'is_surge': 1,
  'surge_amount': 30.0,
  'is_turbo_plus': 0,
  'turbo_plus_amount': None,
  'is_reservation': 0,
  'reservation_amount': None,
  'is_priority': 0,
  'priority_amount': None,
  'is_exclusive': 1,
  'is_vip': 1,
  'is_identity_verified': 0,
  'is_long_trip': 0,
  'is_multiple_destinations': 0,
  'is_teens': 0,
  'rider_star_rating': 4.79,
  'rider_trip_count': 6888.0},
 {'image_filename': 'IMG_1691.PNG',
  'offer_id': 'OF02768',
  'session_fk': 'SID0038',
  'image_content_hash': '94511da5ecc5...',
  'offer_timestamp': '2025-09-18 15:32:57',
  'upfront_fare': '###.##',
  'product_category': 'business_comfort',
  'time_to_pickup_sec': 480.0,
  'dist_to_pickup_km': 1.7,
  'est_trip_time_sec': 2580.0,
  'est_trip_dist_km': 13.4,
  'pickup_address': 'lomas de chapultepec',
  'dropoff_address': 'Carlos Lazo ####, Col Santa Fe Tlayapaca Álvaro Obregón, 01389 Ciudad de México, Ciudad de '
                     'México - Santa Fe',
  'pickup_lat': '19.42####',
  'pickup_lon': '-99.21####',
  'dropoff_lat': '19.35####',
  'dropoff_lon': '-99.25####',
  'is_surge': 0,
  'surge_amount': None,
  'is_turbo_plus': 0,
  'turbo_plus_amount': None,
  'is_reservation': 0,
  'reservation_amount': None,
  'is_priority': 0,
  'priority_amount': None,
  'is_exclusive': 1,
  'is_vip': 1,
  'is_identity_verified': 0,
  'is_long_trip': 0,
  'is_multiple_destinations': 0,
  'is_teens': 0,
  'rider_star_rating': 4.78,
  'rider_trip_count': 2118.0},
 {'image_filename': 'IMG_4346.PNG',
  'offer_id': 'OF03982',
  'session_fk': 'SID0052',
  'image_content_hash': 'f3bf9140fd64...',
  'offer_timestamp': '2025-09-25 19:13:35',
  'upfront_fare': '###.##',
  'product_category': 'uberx',
  'time_to_pickup_sec': 1440.0,
  'dist_to_pickup_km': 2.9,
  'est_trip_time_sec': 3000.0,
  'est_trip_dist_km': 9.3,
  'pickup_address': 'avenida general pedro antonio de los santos, condesa / roma',
  'dropoff_address': 'Prol. P.º de la Reforma ####, Santa Fe, Zedec Sta Fé, Álvaro Obregón, 01310 Ciudad de México, '
                     'CDMX, México - Santa Fe',
  'pickup_lat': '19.41####',
  'pickup_lon': '-99.18####',
  'dropoff_lat': '19.37####',
  'dropoff_lon': '-99.25####',
  'is_surge': 1,
  'surge_amount': 12.0,
  'is_turbo_plus': 1,
  'turbo_plus_amount': 55.37,
  'is_reservation': 0,
  'reservation_amount': None,
  'is_priority': 0,
  'priority_amount': None,
  'is_exclusive': 0,
  'is_vip': 1,
  'is_identity_verified': 0,
  'is_long_trip': 0,
  'is_multiple_destinations': 0,
  'is_teens': 0,
  'rider_star_rating': 4.69,
  'rider_trip_count': 629.0}]

_DF_SILVER_RECORDS = [{'image_filename': 'IMG_0038.PNG',
  'dropoff_polygon_name': 'unassigned',
  'dropoff_h3_hex_id': '894995b9417ffff',
  'dropoff_hdbscan_name': 'terminal_1_aicm'},
 {'image_filename': 'IMG_6624.PNG',
  'dropoff_polygon_name': 'palmas_jp_morgan',
  'dropoff_h3_hex_id': '894995bac0fffff',
  'dropoff_hdbscan_name': 'el_semaforo_de_palmas'},
 {'image_filename': 'IMG_3679.PNG',
  'dropoff_polygon_name': 'universidad_anahuac',
  'dropoff_h3_hex_id': '894995b1187ffff',
  'dropoff_hdbscan_name': 'lomas_anahuac'},
 {'image_filename': 'IMG_9277.PNG',
  'dropoff_polygon_name': 'tamarindos',
  'dropoff_h3_hex_id': '894995b1557ffff',
  'dropoff_hdbscan_name': 'tamarindos'},
 {'image_filename': 'IMG_1691.PNG',
  'dropoff_polygon_name': 'santa_fe_tec',
  'dropoff_h3_hex_id': '894995b33cfffff',
  'dropoff_hdbscan_name': 'santa_fe_itesm'},
 {'image_filename': 'IMG_3428.PNG',
  'dropoff_polygon_name': 'bondojito_asf',
  'dropoff_h3_hex_id': '894995b12cbffff',
  'dropoff_hdbscan_name': 'observatorio'},
 {'image_filename': 'IMG_9029.PNG',
  'dropoff_polygon_name': 'vialidad_de_la_barranca',
  'dropoff_h3_hex_id': '894995b0217ffff',
  'dropoff_hdbscan_name': 'vialidad_de_la_barranca'},
 {'image_filename': 'IMG_4346.PNG',
  'dropoff_polygon_name': 'sante_fe_patio',
  'dropoff_h3_hex_id': '894995b15cbffff',
  'dropoff_hdbscan_name': 'santa_fe_patio'},
 {'image_filename': 'IMG_2793.PNG',
  'dropoff_polygon_name': 'santa_fe_ibero',
  'dropoff_h3_hex_id': '894995b3367ffff',
  'dropoff_hdbscan_name': 'santa_fe_core'},
 {'image_filename': 'IMG_5813.PNG',
  'dropoff_polygon_name': 'roma_condesa_2',
  'dropoff_h3_hex_id': '894995ba1d3ffff',
  'dropoff_hdbscan_name': 'tacubaya'}]

_DF_DTYPES_RECORDS = [{'column_name': 'offer_id', 'data_type': 'STRING'},
 {'column_name': 'session_fk', 'data_type': 'STRING'},
 {'column_name': 'ocr_fk', 'data_type': 'STRING'},
 {'column_name': 'image_content_hash', 'data_type': 'STRING'},
 {'column_name': 'offer_timestamp', 'data_type': 'STRING'},
 {'column_name': 'upfront_fare', 'data_type': 'FLOAT64'},
 {'column_name': 'time_to_pickup_sec', 'data_type': 'FLOAT64'},
 {'column_name': 'dist_to_pickup_km', 'data_type': 'FLOAT64'},
 {'column_name': 'est_trip_time_sec', 'data_type': 'FLOAT64'},
 {'column_name': 'est_trip_dist_km', 'data_type': 'FLOAT64'},
 {'column_name': 'pickup_address', 'data_type': 'STRING'},
 {'column_name': 'dropoff_address', 'data_type': 'STRING'},
 {'column_name': 'pickup_lat', 'data_type': 'FLOAT64'},
 {'column_name': 'pickup_lon', 'data_type': 'FLOAT64'},
 {'column_name': 'dropoff_lat', 'data_type': 'FLOAT64'},
 {'column_name': 'dropoff_lon', 'data_type': 'FLOAT64'},
 {'column_name': 'is_surge', 'data_type': 'INT64'},
 {'column_name': 'surge_amount', 'data_type': 'FLOAT64'},
 {'column_name': 'is_turbo_plus', 'data_type': 'INT64'},
 {'column_name': 'turbo_plus_amount', 'data_type': 'FLOAT64'},
 {'column_name': 'is_reservation', 'data_type': 'INT64'},
 {'column_name': 'reservation_amount', 'data_type': 'FLOAT64'},
 {'column_name': 'is_priority', 'data_type': 'INT64'},
 {'column_name': 'priority_amount', 'data_type': 'FLOAT64'},
 {'column_name': 'is_exclusive', 'data_type': 'INT64'},
 {'column_name': 'is_vip', 'data_type': 'INT64'},
 {'column_name': 'is_identity_verified', 'data_type': 'INT64'},
 {'column_name': 'is_long_trip', 'data_type': 'INT64'},
 {'column_name': 'is_multiple_destinations', 'data_type': 'INT64'},
 {'column_name': 'is_teens', 'data_type': 'INT64'},
 {'column_name': 'rider_star_rating', 'data_type': 'FLOAT64'},
 {'column_name': 'rider_trip_count', 'data_type': 'FLOAT64'},
 {'column_name': 'time_in_session_sec', 'data_type': 'FLOAT64'},
 {'column_name': 'session_progress_ratio', 'data_type': 'FLOAT64'},
 {'column_name': 'inferred_agent_lat', 'data_type': 'FLOAT64'},
 {'column_name': 'inferred_agent_lon', 'data_type': 'FLOAT64'},
 {'column_name': 'inferred_agent_bearing', 'data_type': 'FLOAT64'},
 {'column_name': 'inferred_agent_speed_mps', 'data_type': 'FLOAT64'},
 {'column_name': 'is_imputed', 'data_type': 'INT64'},
 {'column_name': 'special_note_raw', 'data_type': 'STRING'},
 {'column_name': 'comment_1', 'data_type': 'STRING'},
 {'column_name': 'comment_2', 'data_type': 'STRING'},
 {'column_name': 'product_category_fk', 'data_type': 'INT64'},
 {'column_name': 'offer_action_fk', 'data_type': 'INT64'},
 {'column_name': 'reason_primary_fk', 'data_type': 'FLOAT64'},
 {'column_name': 'post_offer_status_fk', 'data_type': 'INT64'},
 {'column_name': 'driver_state_at_request_fk', 'data_type': 'INT64'},
 {'column_name': 'outcome_fk', 'data_type': 'FLOAT64'},
 {'column_name': 'interpolation_quality_fk', 'data_type': 'FLOAT64'},
 {'column_name': 'record_status_fk', 'data_type': 'INT64'}]

# Engine 2 carousel: 10 hand-picked example offers with mock raw/cleaned OCR
# JSON side-by-side, used to illustrate the normalization step in the UI.
ENGINE2_OFFERS: list[dict] = [
    {
        "img": "01_IMG_1691.PNG",
        "confidence": 0.97, "warnings": [],
        "ocr_json": '{\n  "upfront_fare_raw": "$██.██",\n  "product_type":     "UberX",\n  "pickup_address":   "██████████, Col. ████████, CDMX",\n  "dropoff_address":  "████████████████, Col. ████████, CDMX",\n  "pickup_eta_min":   █,\n  "trip_distance_km": █.█,\n  "surge_indicator":  false,\n  "ocr_confidence":   0.97,\n  "parse_warnings":   []\n}',
        "cleaned": [
            ("upfront_fare",    '"$██.██"',        "██.██",     "FLOAT",    "—"),
            ("product_type",    '"UberX"',         "uberx",     "VARCHAR",  "—"),
            ("pickup_address",  '"██████, CDMX"',  "██████",    "VARCHAR",  "geocode_pending"),
            ("dropoff_address", '"██████, CDMX"',  "██████",    "VARCHAR",  "—"),
            ("pickup_eta_min",  "█",               "█",         "INT",      "—"),
            ("surge_indicator", "false",           "0",         "BOOL→INT", "—"),
        ],
    },
    {
        "img": "02_IMG_3428.PNG",
        "confidence": 0.94, "warnings": ["surge_detected"],
        "ocr_json": '{\n  "upfront_fare_raw": "$███.██",\n  "product_type":     "Comfort",\n  "pickup_address":   "████████████████, Col. ████, CDMX",\n  "dropoff_address":  "████████████, Col. ████████, CDMX",\n  "pickup_eta_min":   ██,\n  "trip_distance_km": ██.█,\n  "surge_indicator":  true,\n  "ocr_confidence":   0.94,\n  "parse_warnings":   ["surge_detected"]\n}',
        "cleaned": [
            ("upfront_fare",    '"$███.██"',       "███.██",    "FLOAT",    "surge_flag"),
            ("product_type",    '"Comfort"',       "comfort",   "VARCHAR",  "—"),
            ("pickup_address",  '"████████, CDMX"',"████████",  "VARCHAR",  "—"),
            ("dropoff_address", '"████████, CDMX"',"████████",  "VARCHAR",  "geocode_pending"),
            ("pickup_eta_min",  "██",              "██",        "INT",      "high_eta_warning"),
            ("surge_indicator", "true",            "1",         "BOOL→INT", "surge_flag"),
        ],
    },
    {
        "img": "03_IMG_4346.PNG",
        "confidence": 0.99, "warnings": [],
        "ocr_json": '{\n  "upfront_fare_raw": "$██.██",\n  "product_type":     "UberX",\n  "pickup_address":   "█████████, Col. ████████, CDMX",\n  "dropoff_address":  "███████████████, Col. ████, CDMX",\n  "pickup_eta_min":   █,\n  "trip_distance_km": █.█,\n  "surge_indicator":  false,\n  "ocr_confidence":   0.99,\n  "parse_warnings":   []\n}',
        "cleaned": [
            ("upfront_fare",    '"$██.██"',        "██.██",     "FLOAT",    "—"),
            ("product_type",    '"UberX"',         "uberx",     "VARCHAR",  "—"),
            ("pickup_address",  '"█████████, CDMX"',"█████████","VARCHAR",  "—"),
            ("dropoff_address", '"███████, CDMX"', "███████",   "VARCHAR",  "—"),
            ("pickup_eta_min",  "█",               "█",         "INT",      "—"),
            ("surge_indicator", "false",           "0",         "BOOL→INT", "—"),
        ],
    },
    {
        "img": "04_IMG_5813.PNG",
        "confidence": 0.91, "warnings": ["low_confidence_address"],
        "ocr_json": '{\n  "upfront_fare_raw": "$████.██",\n  "product_type":     "Premier",\n  "pickup_address":   "████████████████, Col. ████████, CDMX",\n  "dropoff_address":  "██████████████████████, CDMX",\n  "pickup_eta_min":   ██,\n  "trip_distance_km": ██.█,\n  "surge_indicator":  false,\n  "ocr_confidence":   0.91,\n  "parse_warnings":   ["low_confidence_address"]\n}',
        "cleaned": [
            ("upfront_fare",    '"$████.██"',      "████.██",   "FLOAT",    "—"),
            ("product_type",    '"Premier"',       "premier",   "VARCHAR",  "—"),
            ("pickup_address",  '"████████, CDMX"',"████████",  "VARCHAR",  "—"),
            ("dropoff_address", '"██████, CDMX"',  "██████",    "VARCHAR",  "low_conf_geocode"),
            ("pickup_eta_min",  "██",              "██",        "INT",      "—"),
            ("surge_indicator", "false",           "0",         "BOOL→INT", "—"),
        ],
    },
    {
        "img": "05_IMG_6624.PNG",
        "confidence": 0.98, "warnings": [],
        "ocr_json": '{\n  "upfront_fare_raw": "$██.██",\n  "product_type":     "UberX",\n  "pickup_address":   "███████████, Col. ████, CDMX",\n  "dropoff_address":  "█████████████, Col. ████████, CDMX",\n  "pickup_eta_min":   █,\n  "trip_distance_km": █.█,\n  "surge_indicator":  false,\n  "ocr_confidence":   0.98,\n  "parse_warnings":   []\n}',
        "cleaned": [
            ("upfront_fare",    '"$██.██"',        "██.██",     "FLOAT",    "—"),
            ("product_type",    '"UberX"',         "uberx",     "VARCHAR",  "—"),
            ("pickup_address",  '"███████, CDMX"', "███████",   "VARCHAR",  "—"),
            ("dropoff_address", '"█████████, CDMX"',"█████████","VARCHAR",  "geocode_pending"),
            ("pickup_eta_min",  "█",               "█",         "INT",      "—"),
            ("surge_indicator", "false",           "0",         "BOOL→INT", "—"),
        ],
    },
    {
        "img": "06_IMG_0038.PNG",
        "confidence": 0.96, "warnings": [],
        "ocr_json": '{\n  "upfront_fare_raw": "$██.██",\n  "product_type":     "UberX",\n  "pickup_address":   "████████████, Col. ████, CDMX",\n  "dropoff_address":  "██████████, Col. ████████, CDMX",\n  "pickup_eta_min":   █,\n  "trip_distance_km": █.█,\n  "surge_indicator":  false,\n  "ocr_confidence":   0.96,\n  "parse_warnings":   []\n}',
        "cleaned": [
            ("upfront_fare",    '"$██.██"',        "██.██",     "FLOAT",    "—"),
            ("product_type",    '"UberX"',         "uberx",     "VARCHAR",  "—"),
            ("pickup_address",  '"████████, CDMX"',"████████",  "VARCHAR",  "—"),
            ("dropoff_address", '"██████, CDMX"',  "██████",    "VARCHAR",  "—"),
            ("pickup_eta_min",  "█",               "█",         "INT",      "—"),
            ("surge_indicator", "false",           "0",         "BOOL→INT", "—"),
        ],
    },
    {
        "img": "07_IMG_3679.PNG",
        "confidence": 0.95, "warnings": ["low_confidence_address"],
        "ocr_json": '{\n  "upfront_fare_raw": "$███.██",\n  "product_type":     "UberX",\n  "pickup_address":   "██████████████, Col. ████, CDMX",\n  "dropoff_address":  "████████████████, Col. ████, CDMX",\n  "pickup_eta_min":   ██,\n  "trip_distance_km": ██.█,\n  "surge_indicator":  false,\n  "ocr_confidence":   0.95,\n  "parse_warnings":   ["low_confidence_address"]\n}',
        "cleaned": [
            ("upfront_fare",    '"$███.██"',       "███.██",    "FLOAT",    "—"),
            ("product_type",    '"UberX"',         "uberx",     "VARCHAR",  "—"),
            ("pickup_address",  '"████████, CDMX"',"████████",  "VARCHAR",  "—"),
            ("dropoff_address", '"████████, CDMX"',"████████",  "VARCHAR",  "low_conf_geocode"),
            ("pickup_eta_min",  "██",              "██",        "INT",      "—"),
            ("surge_indicator", "false",           "0",         "BOOL→INT", "—"),
        ],
    },
    {
        "img": "08_IMG_9029.PNG",
        "confidence": 0.98, "warnings": [],
        "ocr_json": '{\n  "upfront_fare_raw": "$██.██",\n  "product_type":     "Comfort",\n  "pickup_address":   "█████████████, Col. ████████, CDMX",\n  "dropoff_address":  "███████████, Col. ████, CDMX",\n  "pickup_eta_min":   █,\n  "trip_distance_km": █.█,\n  "surge_indicator":  false,\n  "ocr_confidence":   0.98,\n  "parse_warnings":   []\n}',
        "cleaned": [
            ("upfront_fare",    '"$██.██"',        "██.██",     "FLOAT",    "—"),
            ("product_type",    '"Comfort"',       "comfort",   "VARCHAR",  "—"),
            ("pickup_address",  '"█████████, CDMX"',"█████████","VARCHAR",  "—"),
            ("dropoff_address", '"███████, CDMX"', "███████",   "VARCHAR",  "geocode_pending"),
            ("pickup_eta_min",  "█",               "█",         "INT",      "—"),
            ("surge_indicator", "false",           "0",         "BOOL→INT", "—"),
        ],
    },
    {
        "img": "09_IMG_2793.PNG",
        "confidence": 0.93, "warnings": ["surge_detected"],
        "ocr_json": '{\n  "upfront_fare_raw": "$███.██",\n  "product_type":     "UberX",\n  "pickup_address":   "██████████, Col. ████████, CDMX",\n  "dropoff_address":  "████████████████████, CDMX",\n  "pickup_eta_min":   ██,\n  "trip_distance_km": ██.█,\n  "surge_indicator":  true,\n  "ocr_confidence":   0.93,\n  "parse_warnings":   ["surge_detected"]\n}',
        "cleaned": [
            ("upfront_fare",    '"$███.██"',       "███.██",    "FLOAT",    "surge_flag"),
            ("product_type",    '"UberX"',         "uberx",     "VARCHAR",  "—"),
            ("pickup_address",  '"██████, CDMX"',  "██████",    "VARCHAR",  "—"),
            ("dropoff_address", '"████████, CDMX"',"████████",  "VARCHAR",  "—"),
            ("pickup_eta_min",  "██",              "██",        "INT",      "high_eta_warning"),
            ("surge_indicator", "true",            "1",         "BOOL→INT", "surge_flag"),
        ],
    },
    {
        "img": "10_IMG_9277.PNG",
        "confidence": 0.97, "warnings": [],
        "ocr_json": '{\n  "upfront_fare_raw": "$██.██",\n  "product_type":     "UberX",\n  "pickup_address":   "████████████, Col. ████, CDMX",\n  "dropoff_address":  "██████████████, Col. ████████, CDMX",\n  "pickup_eta_min":   █,\n  "trip_distance_km": █.█,\n  "surge_indicator":  false,\n  "ocr_confidence":   0.97,\n  "parse_warnings":   []\n}',
        "cleaned": [
            ("upfront_fare",    '"$██.██"',        "██.██",     "FLOAT",    "—"),
            ("product_type",    '"UberX"',         "uberx",     "VARCHAR",  "—"),
            ("pickup_address",  '"████████, CDMX"',"████████",  "VARCHAR",  "—"),
            ("dropoff_address", '"██████████, CDMX"',"██████████","VARCHAR", "—"),
            ("pickup_eta_min",  "█",               "█",         "INT",      "—"),
            ("surge_indicator", "false",           "0",         "BOOL→INT", "—"),
        ],
    },
]


def obf_fare(v):
    """Replaces every digit in an upfront fare string with #."""
    if v is None:
        return v
    return re.sub(r'\d', '#', str(v))


def obf_address(v):
    """Masks the street-number portion of an address; preserves 5-digit zip codes."""
    if v is None:
        return v
    return re.sub(r'\b(?!\d{5}\b)\d+[\w-]*\b', '####', str(v), count=1)


def obf_hash(v):
    """Truncates a hash string to 12 chars + ellipsis."""
    if v is None:
        return v
    s = str(v)
    return s[:12] + "..." if len(s) > 12 else s


def obf_latlon(v):
    """Keeps 2 decimal digits of a lat/lon value and masks the rest."""
    if v is None:
        return v
    s = str(v)
    dot = s.find(".")
    if dot == -1:
        return s
    return s[:dot + 3] + "####"
